import {NextResponse} from "next/server";import { getAdminContext } from "@/lib/admin/auth";
async function admin(){ return getAdminContext(); }
export async function GET(){const {supabase:s,user}=await admin();if(!user)return NextResponse.json({error:"Administrator access required."},{status:403});const {data,error}=await s.rpc("zynth_admin_list_strategies",{p_admin_id:user.id});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({strategies:Array.isArray(data)?data:[]});}
export async function POST(req:Request){const {supabase:s,user}=await admin();if(!user)return NextResponse.json({error:"Administrator access required."},{status:403});const b=await req.json().catch(()=>({}));
 if(b.action==="intelligence_config"){const {data,error}=await s.rpc("zynth_admin_set_strategy_intelligence_config",{p_admin_id:user.id,p_strategy_id:String(b.strategyId||""),p_maximum_capacity:b.maximumCapacity===""||b.maximumCapacity==null?null:Number(b.maximumCapacity),p_redemption_window_days:b.redemptionWindowDays===""||b.redemptionWindowDays==null?null:Number(b.redemptionWindowDays),p_processing_time_min_business_days:b.processingMin===""||b.processingMin==null?null:Number(b.processingMin),p_processing_time_max_business_days:b.processingMax===""||b.processingMax==null?null:Number(b.processingMax),p_lock_period_days:b.lockPeriodDays===""||b.lockPeriodDays==null?null:Number(b.lockPeriodDays)});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json(data);} if(b.action==="risk_controls"){const {data,error}=await s.rpc("zynth_admin_set_strategy_risk_controls",{p_admin_id:user.id,p_strategy_id:String(b.strategyId||""),p_maximum_drawdown_pct:b.maximumDrawdownPct===""||b.maximumDrawdownPct==null?null:Number(b.maximumDrawdownPct),p_daily_loss_limit_pct:b.dailyLossLimitPct===""||b.dailyLossLimitPct==null?null:Number(b.dailyLossLimitPct),p_maximum_aum:b.maximumAum===""||b.maximumAum==null?null:Number(b.maximumAum),p_maximum_investor_allocation:b.maximumInvestorAllocation===""||b.maximumInvestorAllocation==null?null:Number(b.maximumInvestorAllocation),p_maximum_strategy_allocation_pct:b.maximumStrategyAllocationPct===""||b.maximumStrategyAllocationPct==null?null:Number(b.maximumStrategyAllocationPct),p_minimum_liquidity_reserve:b.minimumLiquidityReserve===""||b.minimumLiquidityReserve==null?null:Number(b.minimumLiquidityReserve),p_emergency_freeze_threshold_pct:b.emergencyFreezeThresholdPct===""||b.emergencyFreezeThresholdPct==null?null:Number(b.emergencyFreezeThresholdPct)});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json(data);}

 if(b.action==="delete"){const {data,error}=await s.rpc("zynth_admin_delete_strategy",{p_admin_id:user.id,p_strategy_id:b.strategyId});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json(data);}
 if(b.action==="approve"||b.action==="pause"||b.action==="archive"){const status=b.action==="approve"?"active":b.action==="pause"?"paused":"archived";const {data,error}=await s.rpc("zynth_admin_set_strategy",{p_admin_id:user.id,p_strategy_id:b.strategyId,p_name:String(b.name||""),p_description:String(b.description||""),p_trader_id:b.traderId||null,p_starting_balance:Number(b.startingBalance||0),p_minimum_investment:Number(b.minimumInvestment||0),p_maximum_investment:b.maximumInvestment!=null&&b.maximumInvestment!==""?Number(b.maximumInvestment):null,p_status:status});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json(data);}
 const {data,error}=await s.rpc("zynth_admin_set_strategy",{p_admin_id:user.id,p_strategy_id:b.strategyId||null,p_name:String(b.name||""),p_description:String(b.description||""),p_trader_id:b.traderId||null,p_starting_balance:Number(b.startingBalance||0),p_minimum_investment:Number(b.minimumInvestment||0),p_maximum_investment:b.maximumInvestment!=null&&b.maximumInvestment!==""?Number(b.maximumInvestment):null,p_status:String(b.status||"active")});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json(data);
}