"use client";import {useEffect,useState} from "react";import {ArrowUpRight,CheckCircle2,Clock3,Plus,ShieldCheck,UploadCloud} from "lucide-react";
const money=(n:any)=>`₦${Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export default function TraderPage(){const[data,setData]=useState<any>({strategies:[],reports:[],profile:null}),[selected,setSelected]=useState(""),[balance,setBalance]=useState(""),[dep,setDep]=useState("0"),[wd,setWd]=useState("0"),[evidence,setEvidence]=useState(""),[note,setNote]=useState(""),[msg,setMsg]=useState("");
 async function load(){const r=await fetch("/api/trader/overview",{cache:"no-store"});const d=await r.json();if(r.ok){setData(d);setSelected(x=>x||d.strategies?.[0]?.id||"")}}useEffect(()=>{load()},[]);
 const strategy=data.strategies.find((x:any)=>x.id===selected);
 async function submit(){setMsg("");const r=await fetch("/api/trader/report",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({strategyId:selected,reportDate:new Date().toISOString().slice(0,10),closingBalance:Number(balance),externalDeposit:Number(dep||0),externalWithdrawal:Number(wd||0),evidenceUrl:evidence,note,positionsFlat:true})});const d=await r.json();setMsg(r.ok?"Daily report submitted. Awaiting admin confirmation.":d.error||"Report failed.");if(r.ok){setBalance("");await load()}}
 return <section className="dashboard-content"><header className="dashboard-header"><div><span className="eyebrow">ZYNTH / TRADER DESK</span><h1>Trading operations.</h1><p>Report raw closing balances. ZYNTH calculates performance after admin verification.</p></div><span className="secure-chip"><ShieldCheck size={14}/> {data.profile?.status||"Trader"}</span></header>
 <section className="trader-summary"><div><span>Trader profile</span><strong>{data.profile?.display_name||data.user?.full_name||"Trader"}</strong><small>{data.profile?.country||"—"} · {data.profile?.years_experience||0} years experience</small></div><div><span>Strategies</span><strong>{data.strategies.length}</strong><small>Drafts and live operations</small></div><div><span>Reporting model</span><strong>Manual verify</strong><small>Admin confirmation required</small></div></section>
 <section className="panel"><div className="panel-head"><div><span className="muted">STRATEGY BOOK</span><h2>Your strategies</h2></div><span className="status-badge"><i/> CONTROLLED</span></div><div className="trader-strategy-grid">{data.strategies.map((s:any)=><button key={s.id} className={selected===s.id?"trader-strategy-card active":"trader-strategy-card"} onClick={()=>setSelected(s.id)}><span>{s.status}</span><b>{s.name}</b><strong>{money(s.current_reported_balance||s.starting_balance)}</strong><small>NAV {Number(s.nav||0).toFixed(2)} · Cutoff {String(s.cutoff_time).slice(0,5)}</small></button>)}{!data.strategies.length&&<div className="premium-empty"><Plus size={20}/><h3>No strategy assigned</h3><p>An administrator must create and assign a strategy before you can submit performance.</p></div>}</div></section>
 {strategy&&<><section className="wealth-hero"><div className="wealth-main"><div className="wealth-label"><span>{strategy.name}</span><span className="secure-chip"><ShieldCheck size={13}/> {strategy.status}</span></div><strong>{money(strategy.current_reported_balance||strategy.starting_balance)}</strong><div className="wealth-breakdown"><span>Last confirmed trader balance</span><span>NAV {Number(strategy.nav).toFixed(2)}</span></div></div><div className="wealth-side"><div><span>Cutoff</span><b>{String(strategy.cutoff_time).slice(0,5)}</b></div><div><span>Minimum investment</span><b>{money(strategy.minimum_investment)}</b></div><div><span>Positions</span><b>{strategy.require_flat_day?"Flat required":"Flexible"}</b></div></div></section>
 <section className="dashboard-grid"><section className="panel"><div className="panel-head"><div><span className="muted">DAILY REPORT</span><h2>Submit closing balance</h2></div><span className="status-badge"><i/> ADMIN REVIEW</span></div><label className="input-label">CLOSING BALANCE</label><div className="money-input"><span>₦</span><input inputMode="decimal" value={balance} onChange={e=>setBalance(e.target.value)} placeholder="220000"/></div><div className="settings-grid"><label><span>External deposits</span><input value={dep} onChange={e=>setDep(e.target.value)} inputMode="decimal"/></label><label><span>External withdrawals</span><input value={wd} onChange={e=>setWd(e.target.value)} inputMode="decimal"/></label></div><label className="setting-textarea"><span>Evidence link</span><input value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Secure screenshot/evidence URL"/></label><label className="setting-textarea"><span>Trader note</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional operational note"/></label><button className="primary full-button" onClick={submit} disabled={!balance}><UploadCloud size={16}/> Submit report <ArrowUpRight size={16}/></button>{msg&&<div className="notice">{msg}</div>}</section><section className="panel"><div className="panel-head"><div><span className="muted">CONTROLLED FLOW</span><h2>Settlement lifecycle</h2></div></div>{[["01","Report","Closing balance + external capital movement."],["02","Verify","Admin reviews evidence and calculations."],["03","Settle","NAV and investor positions update atomically."]].map(x=><div className="info-step" key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div></div>)}</section></section>
 <section className="panel"><div className="panel-head"><div><span className="muted">REPORT HISTORY</span><h2>Recent submissions</h2></div></div><div className="activity-list">{data.reports.filter((r:any)=>r.strategy_id===selected).map((r:any)=><div className="activity-row" key={r.id}><span className={`activity-icon ${r.status==="confirmed"?"positive":"neutral"}`}>{r.status==="confirmed"?<CheckCircle2 size={16}/>:<Clock3 size={16}/>}</span><span className="activity-info"><b>{new Date(r.report_date).toLocaleDateString("en-NG",{day:"numeric",month:"short",year:"numeric"})}</b><small>Open {money(r.opening_balance)} → Close {money(r.reported_closing_balance)} · {Number(r.reported_return_pct||0).toFixed(2)}%</small></span><strong>{String(r.status).toUpperCase()}</strong></div>)}</div></section></>}
 </section>}