"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Clock3, Copy, LoaderCircle, ShieldCheck, XCircle } from "lucide-react";

const naira=(n:number)=>`₦${Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const labels:any={pending:"Submitted",under_review:"Under review",processing:"Processing",paid:"Paid",rejected:"Rejected",cancelled:"Cancelled",failed:"Failed"};
export default function WithdrawalDetail({params}:{params:{id:string}}){
 const [w,setW]=useState<any>(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
 const load=()=>fetch(`/api/withdrawals/${params.id}`).then(r=>r.ok?r.json():null).then(d=>setW(d?.withdrawal||null)).catch(()=>{});
 useEffect(()=>{load()},[]);
 async function cancel(){if(!confirm("Cancel this withdrawal? The reserved gross amount will be returned to your available balance."))return;setBusy(true);setMsg("");try{const r=await fetch("/api/withdrawals/cancel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({withdrawalId:params.id})});const d=await r.json();if(!r.ok){setMsg(d.error||"Unable to cancel.");return}setMsg(`${naira(Number(d.refunded||0))} returned to your available balance.`);load()}finally{setBusy(false)}}
 if(!w)return <section className="dashboard-content"><Link href="/dashboard/transactions" className="text-action"><ArrowLeft size={14}/> Back to Activity</Link><div className="panel" style={{marginTop:20}}>Loading withdrawal…</div></section>;
 const steps=[["pending","Submitted",w.created_at],["under_review","Under review",w.reviewed_at],["processing","Processing",w.processing_at],["paid","Paid",w.paid_at]];
 const terminal=["rejected","cancelled","failed"].includes(w.status);
 const activeIndex=Math.max(0,steps.findIndex((s:any)=>s[0]===w.status));
 return <section className="dashboard-content"><header className="dashboard-header"><div><span className="eyebrow">ZYNTH / WITHDRAWAL</span><h1>Track your withdrawal.</h1><p>Reference <b>{w.reference}</b></p></div><Link className="fund-btn secondary-dark" href="/dashboard/transactions"><ArrowLeft size={16}/> Activity</Link></header>
 <div className="withdraw-detail-grid"><section className="panel withdraw-detail-hero"><div className="detail-status"><span className={"withdraw-status "+w.status}>{labels[w.status]||w.status}</span><span>{new Date(w.created_at).toLocaleString("en-NG",{dateStyle:"medium",timeStyle:"short"})}</span></div><div className="detail-net"><small>YOU RECEIVE</small><strong>{naira(w.net_amount)}</strong><span>{naira(w.gross_amount)} requested · {naira(w.fee_amount)} fee</span></div><div className="detail-reference"><span>WITHDRAWAL REFERENCE</span><b>{w.reference}</b><button onClick={()=>{navigator.clipboard?.writeText(w.reference);setCopied(true);setTimeout(()=>setCopied(false),1500)}}>{copied?<CheckCircle2 size={15}/>:<Copy size={15}/>} {copied?"Copied":"Copy"}</button></div>{msg&&<div className="form-feedback success"><CheckCircle2 size={15}/>{msg}</div>}{w.status==="pending"&&<button className="danger-outline" onClick={cancel} disabled={busy}>{busy?"Cancelling…":"Cancel withdrawal"}</button>}</section>
 <section className="panel"><span className="muted">PAYOUT DESTINATION</span><h2>{w.bank_name}</h2><div className="beneficiary-preview"><b>{w.account_name}</b><span>••••••{String(w.account_number).slice(-4)}</span><small>Bank account</small></div><div className="withdraw-breakdown"><div><span>Gross withdrawal</span><b>{naira(w.gross_amount)}</b></div><div><span>Exit fee ({w.fee_pct}%)</span><b>−{naira(w.fee_amount)}</b></div><div className="net"><span>Net payout</span><b>{naira(w.net_amount)}</b></div></div></section>
 <section className="panel withdraw-timeline"><span className="muted">REQUEST TIMELINE</span><h2>Withdrawal progress</h2>{steps.map((s:any,i:number)=><div className={"timeline-step "+(s[2]?"done":"")+(i===activeIndex&&!terminal?" current":"")} key={s[0]}><span className="timeline-dot">{s[2]?<CheckCircle2 size={13}/>:<Clock3 size={13}/>}</span><div><b>{s[1]}</b><small>{s[2]?new Date(s[2]).toLocaleString("en-NG",{dateStyle:"medium",timeStyle:"short"}):"Waiting"}</small></div></div>)}{terminal&&<div className="timeline-terminal"><XCircle size={16}/><div><b>{labels[w.status]}</b><small>{w.failure_reason||"This withdrawal request is no longer active."}</small></div></div>}</section></div></section>;
}