"use client";
import {useEffect,useState} from "react";
import {CheckCircle2,Clock3,Gift,RefreshCw,ShieldAlert,Users,XCircle} from "lucide-react";
const money=(n:any)=>"₦"+Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});
export default function AdminReferralCenter(){const[d,setD]=useState<any>({});const[busy,setBusy]=useState("");const[n,setN]=useState("");const[saving,setSaving]=useState(false);
async function load(){const r=await fetch("/api/admin/referrals");const j=await r.json();if(r.ok)setD(j);else setN(j.error||"Could not load referral centre.");}
useEffect(()=>{load()},[]);
const s=d.settings||{};async function settings(e:any){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget);const r=await fetch("/api/admin/referrals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"settings",enabled:f.get("enabled")==="on",min:f.get("min"),fixed:f.get("fixed"),percent:f.get("percent"),cap:f.get("cap"),window:f.get("window"),pending:f.get("pending"),max:f.get("max")})});const j=await r.json();setN(r.ok?"Referral settings saved.":j.error||"Save failed.");if(r.ok)await load();setSaving(false);}
async function act(id:string,a:string){setBusy(id);const reason=a==="reject"?window.prompt("Reason for rejection")||"Rejected by administrator":null;const r=await fetch("/api/admin/referrals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:a,rewardId:id,reason})});const j=await r.json();setN(r.ok?(a==="reject"?"Reward rejected.":"Reward credited successfully."):(j.error||"Action failed."));await load();setBusy("");}
return <section className="admin-section referral-admin"><div className="referral-hero"><div><span className="muted">REFERRAL CONTROL CENTER</span><h2>Referral growth, with financial controls.</h2><p>Attribution, qualification, rewards and risk signals stay separated from core investment accounting until a reward is explicitly credited.</p></div><button className="ghost" onClick={load}><RefreshCw size={14}/> Refresh</button></div>{n&&<div className="admin-notice">{n}</div>}
<div className="referral-kpis"><div><Users size={17}/><span>Referrals</span><b>{d.total_referrals||0}</b></div><div><CheckCircle2 size={17}/><span>Qualified</span><b>{d.qualified||0}</b></div><div><Clock3 size={17}/><span>Pending rewards</span><b>{money(d.pending_rewards)}</b></div><div><Gift size={17}/><span>Paid rewards</span><b>{money(d.paid_rewards)}</b></div><div><ShieldAlert size={17}/><span>Investment generated</span><b>{money(d.investment_generated)}</b></div></div>
<div className="referral-admin-grid"><section className="admin-card"><div className="admin-card-head"><div><span className="muted">PROGRAMME SETTINGS</span><h2>Reward rules</h2><p>Changes affect future qualifications.</p></div></div><form className="referral-settings" onSubmit={settings}><label className="toggle-field"><input type="checkbox" name="enabled" defaultChecked={s.enabled}/><span>Programme enabled</span></label><label>Minimum qualifying investment<input name="min" type="number" min="1" defaultValue={s.min_qualifying_investment||10000}/></label><label>Fixed reward<input name="fixed" type="number" min="0" defaultValue={s.fixed_reward||500}/></label><label>Percent reward<input name="percent" type="number" min="0" max="100" step="0.01" defaultValue={s.percent_reward||0}/></label><label>Reward cap<input name="cap" type="number" min="0" defaultValue={s.reward_cap||500}/></label><label>Qualification window (days)<input name="window" type="number" min="1" defaultValue={s.qualification_window_days||30}/></label><label>Pending period (hours)<input name="pending" type="number" min="0" defaultValue={s.pending_period_hours||24}/></label><label>Max rewards / referrer<input name="max" type="number" min="1" defaultValue={s.max_rewards_per_referrer||100}/></label><button className="primary" disabled={saving}>{saving?"Saving…":"Save programme rules"}</button></form></section>
<section className="admin-card"><div className="admin-card-head"><div><span className="muted">REWARD QUEUE</span><h2>Human review before money moves</h2><p>Every credited reward creates a normal ZYNTH transaction and audit record.</p></div></div><div className="referral-reward-list">{(d.rewards||[]).map((r:any)=><div className="referral-reward-row" key={r.id}><div><b>{r.referrer_name}</b><small>{r.referred_name} · {money(r.qualifying_amount)} qualified</small></div><strong>{money(r.reward_amount)}</strong><span className={"ref-status "+r.status}>{r.status}</span>{r.status==="pending"&&<div className="row-actions"><button className="approve" disabled={busy===r.id} onClick={()=>act(r.id,"credit")}><CheckCircle2 size={13}/> Credit</button><button className="reject" disabled={busy===r.id} onClick={()=>act(r.id,"reject")}><XCircle size={13}/> Reject</button></div>}</div>)}{!(d.rewards||[]).length&&<div className="admin-empty"><Gift size={20}/><p>No referral rewards yet.</p></div>}</div></section></div>
<section className="admin-card"><div className="admin-card-head"><div><span className="muted">REFERRAL NETWORK</span><h2>Attribution & risk</h2><p>Review unusual relationships before they become a payout pattern.</p></div></div><div className="admin-table">{(d.referrals||[]).map((r:any)=><div className="admin-row" key={r.id}><div className="admin-person"><span className="avatar">R</span><span><b>{r.referrer_name}</b><small>referred {r.referred_name} · {new Date(r.created_at).toLocaleDateString("en-NG")}</small></span></div><span>{r.status}</span><span>Risk {r.risk_score}/100</span><strong>{(r.risk_flags||[]).length?r.risk_flags.join(", "):"Clear"}</strong></div>)}{!(d.referrals||[]).length&&<div className="admin-empty"><Users size={20}/><p>No referrals yet.</p></div>}</div></section></section>}