"use client";
import {useEffect,useMemo,useState} from "react";
import {Bell,ChevronRight,Clock3,Copy,Edit3,Eye,History,MessageSquare,Plus,Save,Search,Send,ShieldCheck,Trash2,Users,X} from "lucide-react";

type Audience={role:string;funding:string;push_status:string;account_status:string;user_ids:string[]};
const emptyAudience=():Audience=>({role:"investors",funding:"any",push_status:"any",account_status:"active",user_ids:[]});

function audienceLabel(a:Audience){
 const role={all:"All users",investors:"Investors",traders:"Traders",users_except_traders:"Users except traders",admins:"Admins",specific:"Selected users"}[a.role]||"Audience";
 const funding=a.funding==="funded"?" · Funded":a.funding==="unfunded"?" · Never funded":"";
 const push=a.push_status==="disabled_or_no_device"?" · Push unavailable":a.push_status==="enabled"?" · Push enabled":a.push_status==="disabled"?" · Push disabled":a.push_status==="no_device"?" · No active device":"";
 return role+funding+push;
}

export default function AdminBroadcastCenter(){
 const [tab,setTab]=useState<"compose"|"history"|"templates">("compose");
 const [title,setTitle]=useState(""),[body,setBody]=useState(""),[priority,setPriority]=useState("normal"),[actionUrl,setActionUrl]=useState("");
 const [inApp,setInApp]=useState(true),[push,setPush]=useState(true),[audience,setAudience]=useState<Audience>(emptyAudience());
 const [preview,setPreview]=useState<any>(null),[previewLoading,setPreviewLoading]=useState(false),[recipients,setRecipients]=useState<any[]>([]),[showRecipients,setShowRecipients]=useState(false);
 const [notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[drafts,setDrafts]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]),[templates,setTemplates]=useState<any[]>([]);
 const [userQuery,setUserQuery]=useState(""),[userResults,setUserResults]=useState<any[]>([]),[selectedUsers,setSelectedUsers]=useState<any[]>([]);
 const [template,setTemplate]=useState<any>(null);

 async function loadAll(){
  const [h,d,t]=await Promise.all([fetch("/api/admin/broadcast?mode=history",{cache:"no-store"}),fetch("/api/admin/broadcast?mode=drafts",{cache:"no-store"}),fetch("/api/admin/broadcast?mode=templates",{cache:"no-store"})]);
  const hj=await h.json(),dj=await d.json(),tj=await t.json();if(h.ok)setHistory(hj.broadcasts||[]);if(d.ok)setDrafts(dj.drafts||[]);if(t.ok)setTemplates(tj.templates||[]);
 }
 useEffect(()=>{loadAll()},[]);
 useEffect(()=>{const t=window.setTimeout(async()=>{if(audience.role!=="specific"){setUserResults([]);return}const r=await fetch("/api/admin/broadcast?mode=users&q="+encodeURIComponent(userQuery),{cache:"no-store"});const j=await r.json();if(r.ok)setUserResults(j.users||[])},250);return()=>window.clearTimeout(t)},[userQuery,audience.role]);
 useEffect(()=>{setAudience(a=>({...a,user_ids:selectedUsers.map(x=>x.user_id)}))},[selectedUsers]);
 useEffect(()=>{setPreview(null)},[audience.role,audience.funding,audience.push_status,audience.account_status,JSON.stringify(audience.user_ids)]);

 const doPreview=async()=>{setPreviewLoading(true);setNotice("");try{const r=await fetch("/api/admin/broadcast?mode=preview&audience="+encodeURIComponent(JSON.stringify(audience)),{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Preview failed.");setPreview(j.preview);return j.preview}catch(e){setNotice(e instanceof Error?e.message:"Preview failed.")}finally{setPreviewLoading(false)}};
 const loadRecipients=async()=>{setBusy(true);try{const r=await fetch("/api/admin/broadcast?mode=recipients&audience="+encodeURIComponent(JSON.stringify(audience)),{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load recipients.");setRecipients(j.recipients||[]);setShowRecipients(true)}catch(e){setNotice(e instanceof Error?e.message:"Could not load recipients.")}finally{setBusy(false)}};
 const reset=()=>{setTitle("");setBody("");setPriority("normal");setActionUrl("");setAudience(emptyAudience());setSelectedUsers([]);setPreview(null);};
 const saveDraft=async()=>{setBusy(true);const r=await fetch("/api/admin/broadcast",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"draft",title,body,audience,channel_in_app:inApp,channel_push:push,priority,action_url:actionUrl})});const j=await r.json();setNotice(r.ok?"Draft saved.":j.error||"Could not save draft.");if(r.ok)await loadAll();setBusy(false)};
 const sendBroadcast=async()=>{if(!title.trim()||!body.trim()){setNotice("Add a title and message before sending.");return}if(!inApp&&!push){setNotice("Select at least one delivery channel.");return}const resolved=preview||await doPreview();const count=Number(resolved?.recipient_count||0);if(count===0){setNotice("This audience currently has no recipients.");return}if(!window.confirm(`Send this broadcast to ${count} recipient${count===1?"":"s"}? The audience will be snapshotted at send time.`))return;setBusy(true);const r=await fetch("/api/admin/broadcast",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"send",title,body,audience,channel_in_app:inApp,channel_push:push,priority,action_url:actionUrl})});const j=await r.json();setNotice(r.ok?`Broadcast sent to ${j.broadcast?.recipient_count||count} recipients.`:j.error||"Broadcast failed.");if(r.ok){reset();await loadAll()}setBusy(false)};
 const useDraft=(d:any)=>{setTitle(d.title);setBody(d.body);setAudience(d.audience||emptyAudience());setPriority(d.priority||"normal");setActionUrl(d.action_url||"");setInApp(d.channel_in_app!==false);setPush(d.channel_push!==false);setTab("compose")};
 const useTemplate=(t:any)=>{setTitle(t.title);setBody(t.body);setPriority(t.priority||"normal");setActionUrl(t.action_url||"");setTab("compose")};
 const saveTemplate=async()=>{if(!template)return;setBusy(true);const r=await fetch("/api/admin/broadcast",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"template",...template})});const j=await r.json();setNotice(r.ok?"Template saved.":j.error||"Template save failed.");if(r.ok){setTemplate(null);await loadAll()}setBusy(false)};
 const deleteTemplate=async(id:string)=>{if(!window.confirm("Delete this broadcast template?"))return;setBusy(true);const r=await fetch("/api/admin/broadcast",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"delete_template",id})});const j=await r.json();setNotice(r.ok?"Template deleted.":j.error||"Delete failed.");if(r.ok)await loadAll();setBusy(false)};
 const deleteDraft=async(id:string)=>{if(!window.confirm("Delete this draft?"))return;setBusy(true);const r=await fetch("/api/admin/broadcast",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"delete_draft",id})});const j=await r.json();setNotice(r.ok?"Draft deleted.":j.error||"Delete failed.");if(r.ok)await loadAll();setBusy(false)};
 const selectedIds=useMemo(()=>new Set(selectedUsers.map(x=>x.user_id)),[selectedUsers]);

 return <section className="admin-section admin-broadcast-center">
  <section className="broadcast-hero"><div><span className="muted">ZYNTH / COMMUNICATION</span><h2>Messaging broadcast</h2><p>Send targeted, auditable communications without mixing them with system-generated notifications. Audience rules are evaluated server-side before delivery.</p></div><div className="broadcast-hero-mark"><MessageSquare size={22}/><span>CONTROLLED DELIVERY</span></div></section>
  <div className="broadcast-tabs"><button className={tab==="compose"?"active":""} onClick={()=>setTab("compose")}><Send size={14}/> Broadcast</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}><History size={14}/> History <b>{history.length}</b></button><button className={tab==="templates"?"active":""} onClick={()=>setTab("templates")}><Copy size={14}/> Templates <b>{templates.length}</b></button></div>
  {notice&&<div className="admin-notice">{notice}</div>}

  {tab==="compose"&&<div className="broadcast-layout">
   <section className="admin-card broadcast-compose">
    <div className="admin-card-head"><div><span className="muted">COMPOSE</span><h2>New broadcast</h2><p>The audience is resolved and snapshotted server-side when you send.</p></div><span className={"broadcast-priority "+priority}>{priority}</span></div>
    <div className="broadcast-form">
      <label className="wide"><span>Message title <b>Required</b></span><input maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Announcement title"/></label>
      <label className="wide"><span>Message body <b>Required</b></span><textarea maxLength={5000} rows={7} value={body} onChange={e=>setBody(e.target.value)} placeholder="Write the message your audience should receive…"/><small>{body.length}/5000</small></label>
      <div className="broadcast-form-row"><label><span>Priority</span><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></label><label><span>CTA / internal path <small>optional</small></span><input value={actionUrl} onChange={e=>setActionUrl(e.target.value)} placeholder="/dashboard/investments"/></label></div>
    </div>
    <div className="broadcast-section"><div className="broadcast-section-head"><span>AUDIENCE BUILDER</span><small>Combine filters with AND logic</small></div>
      <div className="broadcast-filter-grid">
       <label><span>Role</span><select value={audience.role} onChange={e=>setAudience(a=>({...a,role:e.target.value,user_ids:e.target.value==="specific"?a.user_ids:[]}))}><option value="investors">Investors only</option><option value="traders">Traders only</option><option value="users_except_traders">All users except traders</option><option value="all">All users</option><option value="admins">Admins</option><option value="specific">Specific users</option></select></label>
       <label><span>Funding</span><select value={audience.funding} onChange={e=>setAudience(a=>({...a,funding:e.target.value}))}><option value="any">Any funding state</option><option value="funded">Funded / has funded</option><option value="unfunded">Never funded</option></select></label>
       <label><span>Notification status</span><select value={audience.push_status} onChange={e=>setAudience(a=>({...a,push_status:e.target.value}))}><option value="any">Any notification state</option><option value="enabled">Push enabled</option><option value="disabled">Push disabled</option><option value="no_device">No active device</option><option value="disabled_or_no_device">Push unavailable</option></select></label>
       <label><span>Account</span><select value={audience.account_status} onChange={e=>setAudience(a=>({...a,account_status:e.target.value}))}><option value="active">Active accounts</option><option value="verified">KYC verified</option><option value="unverified">KYC unverified</option><option value="any">Any account status</option></select></label>
      </div>
      {audience.role==="specific"&&<div className="broadcast-user-picker"><div className="broadcast-specific-help"><b>Choose the exact users</b><small>Search by name or email, then tap a user to add them. You can select one or many.</small></div><div className="broadcast-search"><Search size={14}/><input value={userQuery} onChange={e=>setUserQuery(e.target.value)} placeholder="Search name or email…"/></div>{selectedUsers.length>0&&<div className="broadcast-selected">{selectedUsers.map(u=><button key={u.user_id} onClick={()=>setSelectedUsers(xs=>xs.filter(x=>x.user_id!==u.user_id))}>{u.full_name||u.email}<X size={12}/></button>)}</div>}<div className="broadcast-user-results">{userResults.filter(u=>!selectedIds.has(u.user_id)).map(u=><button key={u.user_id} onClick={()=>setSelectedUsers(xs=>[...xs,u])}><span><b>{u.full_name||"Unnamed user"}</b><small>{u.email} · {u.role}</small></span><Plus size={14}/></button>)}</div></div>}
      <div className="broadcast-audience-preview">{preview?<><div className="broadcast-total"><span>RECIPIENTS</span><strong>{preview.recipient_count}</strong></div><div className="broadcast-stats"><span><b>{preview.investors}</b> investors</span><span><b>{preview.traders}</b> traders</span><span><b>{preview.funded}</b> funded</span><span><b>{preview.unfunded}</b> never funded</span><span><b>{preview.push_enabled}</b> push enabled</span><span><b>{Number(preview.push_disabled)+Number(preview.push_no_device)}</b> push unavailable</span></div><button className="text-action" onClick={loadRecipients}>View recipients <ChevronRight size={13}/></button></>:<div><strong>Audience not previewed</strong><small>Resolve the current filters before sending.</small></div>}<button className="ghost" onClick={doPreview} disabled={previewLoading}>{previewLoading?"Calculating…":"Preview audience"}</button></div>
    </div>
    <div className="broadcast-section"><div className="broadcast-section-head"><span>DELIVERY</span><small>Uses the existing ZYNTH notification pipeline</small></div><div className="broadcast-channels"><label><input type="checkbox" checked={inApp} disabled={push} onChange={e=>setInApp(e.target.checked)}/><span><b>In-app notification</b><small>Always appears in the user's ZYNTH notification center.</small></span></label><label><input type="checkbox" checked={push} onChange={e=>setPush(e.target.checked)}/><span><b>Device push</b><small>Only eligible devices receive Web Push.</small></span></label></div></div>
    <footer className="broadcast-actions"><button className="ghost" onClick={saveDraft} disabled={busy}><Save size={14}/> Save draft</button><button className="primary" onClick={sendBroadcast} disabled={busy||!title.trim()||!body.trim()}><Send size={14}/> {busy?"Sending…":"Send broadcast"}</button></footer>
   </section>
   <aside className="broadcast-side">
    <section className="admin-card"><div className="admin-card-head"><div><span className="muted">DRAFTS</span><h2>Saved drafts</h2></div><span className="admin-count">{drafts.length}</span></div>{drafts.slice(0,5).map(d=><div className="broadcast-list-row" key={d.id}><button onClick={()=>useDraft(d)}><b>{d.title}</b><small>{audienceLabel(d.audience||emptyAudience())}</small></button><button className="notification-icon-btn danger" onClick={()=>deleteDraft(d.id)}><Trash2 size={13}/></button></div>)}{!drafts.length&&<div className="broadcast-empty">No drafts yet.</div>}</section>
    <section className="admin-card"><div className="admin-card-head"><div><span className="muted">SAFE DELIVERY</span><h2>Before you send</h2></div><ShieldCheck size={18}/></div><ul className="broadcast-safety"><li>Audience is resolved on the server.</li><li>Recipients are deduplicated.</li><li>Only active accounts enter standard audiences.</li><li>Push-disabled users still receive in-app messages.</li><li>Every campaign keeps an audit snapshot.</li></ul></section>
   </aside>
  </div>}

  {tab==="history"&&<section className="admin-card broadcast-history"><div className="admin-card-head"><div><span className="muted">AUDIT TRAIL</span><h2>Broadcast history</h2><p>Every campaign keeps its audience rules and push delivery counters.</p></div><button className="ghost" onClick={loadAll}><Clock3 size={13}/> Refresh</button></div><div className="broadcast-history-list">{history.map(h=><article key={h.id}><div className="broadcast-history-main"><span className={"broadcast-priority "+h.priority}>{h.priority}</span><h3>{h.title}</h3><p>{h.body}</p><small>{audienceLabel(h.audience||emptyAudience())} · {h.sent_at?new Date(h.sent_at).toLocaleString("en-NG"):"Not sent"}</small></div><div className="broadcast-history-metrics"><b>{h.recipient_count}</b><span>recipients</span><b>{h.push_sent_count}</b><span>push accepted</span><b>{h.push_failed_count}</b><span>push failed</span></div></article>)}{!history.length&&<div className="admin-empty"><History size={22}/><p>No broadcasts have been sent.</p></div>}</div></section>}

  {tab==="templates"&&<section className="admin-card broadcast-templates"><div className="admin-card-head"><div><span className="muted">MESSAGE LIBRARY</span><h2>Broadcast templates</h2><p>Reusable admin-authored messages. Templates never send by themselves.</p></div><button className="primary" onClick={()=>setTemplate({id:null,name:"",category:"custom",title:"",body:"",priority:"normal",action_url:""})}><Plus size={14}/> New template</button></div><div className="broadcast-template-grid">{templates.map(t=><article key={t.id}><div><span>{t.category}</span><h3>{t.name}</h3><strong>{t.title}</strong><p>{t.body}</p></div><footer><button className="ghost" onClick={()=>useTemplate(t)}><Edit3 size={13}/> Use</button><button className="notification-icon-btn" onClick={()=>setTemplate(t)}><Edit3 size={13}/></button><button className="notification-icon-btn danger" onClick={()=>deleteTemplate(t.id)}><Trash2 size={13}/></button></footer></article>)}{!templates.length&&<div className="admin-empty"><Copy size={22}/><p>No broadcast templates yet.</p></div>}</div></section>}

  {template&&<div className="notification-modal-backdrop"><section className="notification-modal" role="dialog" aria-modal="true"><header><div><span className="muted">BROADCAST TEMPLATE</span><h2>{template.id?"Edit template":"New template"}</h2></div><button className="icon-button" onClick={()=>setTemplate(null)}><X size={16}/></button></header><div className="notification-form-grid"><label><span>Name <b>Required</b></span><input value={template.name} onChange={e=>setTemplate({...template,name:e.target.value})}/></label><label><span>Category</span><input value={template.category} onChange={e=>setTemplate({...template,category:e.target.value})}/></label><label className="wide"><span>Title <b>Required</b></span><input value={template.title} onChange={e=>setTemplate({...template,title:e.target.value})}/></label><label className="wide"><span>Body <b>Required</b></span><textarea rows={6} value={template.body} onChange={e=>setTemplate({...template,body:e.target.value})}/></label><label><span>Priority</span><select value={template.priority} onChange={e=>setTemplate({...template,priority:e.target.value})}><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></label><label><span>CTA / path</span><input value={template.action_url||""} onChange={e=>setTemplate({...template,action_url:e.target.value})}/></label></div><footer><button className="ghost" onClick={()=>setTemplate(null)}>Cancel</button><button className="notification-save" onClick={saveTemplate} disabled={busy||!template.name?.trim()||!template.title?.trim()||!template.body?.trim()}><Save size={14}/> Save template</button></footer></section></div>}

  {showRecipients&&<div className="notification-modal-backdrop"><section className="notification-modal broadcast-recipient-modal" role="dialog" aria-modal="true"><header><div><span className="muted">AUDIENCE SNAPSHOT</span><h2>{recipients.length} recipients</h2><p>These are the users matching the current rules.</p></div><button className="icon-button" onClick={()=>setShowRecipients(false)}><X size={16}/></button></header><div className="broadcast-recipient-list">{recipients.map(r=><div key={r.user_id}><span className="avatar">{String(r.full_name||r.email||"?").charAt(0).toUpperCase()}</span><span><b>{r.full_name||"Unnamed user"}</b><small>{r.email} · {r.role} · {r.funded?"Funded":"Never funded"}</small></span><em>{r.push_state}</em></div>)}</div></section></div>}
 </section>;
}