"use client";
import {useEffect,useState} from "react";
import {AlertTriangle,CheckCircle2,KeyRound,RefreshCw,Save,ShieldCheck} from "lucide-react";
const ASSETS=[["usdttrc20","USDT · TRON (TRC20)"],["usdtbsc","USDT · BNB Smart Chain"],["usdterc20","USDT · Ethereum (ERC20)"],["usdtsol","USDT · Solana"],["usdtmatic","USDT · Polygon"],["usdc","USDC"],["usdcspl","USDC · Solana"],["usdcmatic","USDC · Polygon"]];
export default function AdminCryptoSettings({refreshKey}:{refreshKey?:number}){
 const[s,setS]=useState<any>(null),[apiKey,setApiKey]=useState(""),[ipn,setIpn]=useState(""),[busy,setBusy]=useState(false),[testBusy,setTestBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 async function load(){try{const r=await fetch("/api/admin/payment-provider",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to load crypto settings.");setS(d.settings)}catch(e:any){setErr(e.message)}}
 useEffect(()=>{load()},[refreshKey]);
 const toggle=(currency:string)=>setS((x:any)=>({...x,supported_currencies:x.supported_currencies.includes(currency)?x.supported_currencies.filter((v:string)=>v!==currency):[...x.supported_currencies,currency]}));
 async function save(){setBusy(true);setErr("");setMsg("");try{const r=await fetch("/api/admin/payment-provider",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...s,api_key:apiKey,ipn_secret:ipn})});const d=await r.json();if(!r.ok)throw Error(d.error||"Unable to save.");setS(d.settings);setApiKey("");setIpn("");setMsg("NOWPayments configuration saved securely.")}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 async function test(){setTestBusy(true);setErr("");setMsg("");try{const r=await fetch("/api/admin/payment-provider",{method:"POST"});const d=await r.json();if(!r.ok)throw Error(d.error||"Connection test failed.");setMsg(d.message||"Connection verified.");await load()}catch(e:any){setErr(e.message);await load()}finally{setTestBusy(false)}}
 if(err&&!s)return <div className="zcall warning"><AlertTriangle size={15}/><span>{err}</span><button className="ghost" onClick={()=>{setErr("");load()}}>Retry</button></div>;
 if(!s)return <div className="admin-empty"><RefreshCw className="spin" size={18}/><p>Loading crypto controls…</p></div>;
 return <section className="crypto-settings"><div className="zstatus"><span>● Crypto {s.enabled?"LIVE":"OFF"}</span><span>● Provider NOWPayments</span><span>● Base NGN</span></div>
 <div className="zcall"><ShieldCheck size={15}/><span><b>Provider secrets are encrypted before storage.</b><br/>The API key and IPN Secret are never returned to the browser after save.</span></div>
 <div className="zg"><label className="zst"><span><b>Enable crypto deposits</b><small>Show cryptocurrency funding as an active payment rail.</small></span><input type="checkbox" checked={!!s.enabled} onChange={e=>setS({...s,enabled:e.target.checked})}/></label><label className="zst"><span><b>Fixed-rate checkout</b><small>Lock the exchange rate when creating a payment.</small></span><input type="checkbox" checked={!!s.fixed_rate} onChange={e=>setS({...s,fixed_rate:e.target.checked})}/></label><label className="zst"><span><b>Crypto fees paid by user</b><small>Pass supported provider fees to the customer.</small></span><input type="checkbox" checked={!!s.fee_paid_by_user} onChange={e=>setS({...s,fee_paid_by_user:e.target.checked})}/></label></div>
 <div className="zcall"><div><b>SUPPORTED ASSET / NETWORKS</b><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8,marginTop:10}}>{ASSETS.map(([key,label])=><button type="button" key={key} className="details" style={{justifyContent:"flex-start",borderColor:s.supported_currencies.includes(key)?"#806431":undefined}} onClick={()=>toggle(key)}>{s.supported_currencies.includes(key)?"✓ ":"＋ "}{label}</button>)}</div></div></div>
 <div className="zg"><label className="zsf"><span>NOWPAYMENTS_API_KEY</span><small>{s.api_key_configured?"Configured · enter a new key only to rotate it.":"Not configured."}</small><div className="secret-input"><KeyRound size={14}/><input type="password" autoComplete="new-password" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={s.api_key_configured?"••••••••••••":"Paste API key"}/></div></label><label className="zsf"><span>NOWPAYMENTS_IPN_SECRET</span><small>{s.ipn_secret_configured?"Configured · enter a new secret only to rotate it.":"Not configured."}</small><div className="secret-input"><KeyRound size={14}/><input type="password" autoComplete="new-password" value={ipn} onChange={e=>setIpn(e.target.value)} placeholder={s.ipn_secret_configured?"••••••••••••":"Paste IPN secret"}/></div></label></div>
 <div className="zfooter"><span>{s.last_test_at?(s.last_test_status==="success"?"Verified":"Last test failed")+" · "+new Date(s.last_test_at).toLocaleString("en-NG"):"No connection test yet."}</span><div style={{display:"flex",gap:8}}><button className="details" disabled={testBusy||!s.api_key_configured} onClick={test}>{testBusy?"Testing…":"Test NOWPayments"}</button><button className="primary" disabled={busy} onClick={save}>{busy?<><Save size={14}/>Saving…</>:<><Save size={14}/>Save crypto settings</>}</button></div></div>{(msg||err)&&<div className={err?"zcall warning":"zcall"}>{err?<AlertTriangle size={14}/>:<CheckCircle2 size={14}/>}<span>{err||msg}</span></div>}
 </section>