"use client";
import {useEffect,useMemo,useState} from "react";
import {Bot,CheckCircle2,Clock3,Pause,Play,Plus,RefreshCw,ShieldCheck,XCircle,Zap} from "lucide-react";

export default function AdminZynthTrade({strategies=[],refreshKey=0,onSaved}:{strategies?:any[];refreshKey?:number;onSaved?:()=>void}){
 const[data,setData]=useState<any>({instances:[],runs:[],reporting_window:{}}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[form,setForm]=useState<any>(null),[reason,setReason]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/zynth-trade",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load ZYNTH Trade.");setData(j)}catch(e:any){alert(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[refreshKey]);
 const active=useMemo(()=>data.instances.filter((x:any)=>x.status==="active").length,[data.instances]);
 async function save(){if(!form)return;setBusy("save");try{const r=await fetch("/api/admin/zynth-trade",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save",...form})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to save.");setForm(null);await load();onSaved?.()}catch(e:any){alert(e.message)}finally{setBusy("")}}
 async function verify(runId:string,approve:boolean){setBusy(runId+approve);try{const r=await fetch("/api/admin/zynth-trade",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"verify",runId,approve,reason})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to update run.");setReason("");await load();onSaved?.()}catch(e:any){alert(e.message)}finally{setBusy("")}}
 return <section className="admin-section zt-center">
  <div className="zt-hero"><div><div className="zt-kicker"><Bot size={13}/> ZYNTH TRADE <i>AUTOMATED STRATEGY CONTROL</i></div><h2>Automated reporting without a second financial engine.</h2><p>ZYNTH Trade uses the existing trader reporting window and the same settlement engine as assigned traders.</p></div><div className="zt-badge"><Zap size={14}/><strong>{active}</strong><span>active instances</span></div></div>
  <div className="zt-grid">
   <div className="zt-card"><span>REPORTING WINDOW</span><strong>{String(data.reporting_window?.start_time||"—").slice(0,5)} — {String(data.reporting_window?.end_time||"—").slice(0,5)}</strong><small>Inherited from Trader Governance · {data.reporting_window?.timezone||"Africa/Lagos"}</small></div>
   <div className="zt-card"><span>PENDING VERIFICATION</span><strong>{data.runs.filter((r:any)=>r.status==="pending_verification").length}</strong><small>Automated runs awaiting operations review</small></div>
   <div className="zt-card"><span>RUNS STORED</span><strong>{data.runs.length}</strong><small>Recent 50 automated runs</small></div>
  </div>
  <div className="zt-card">
   <div className="zt-head"><div><span className="muted">AUTOMATION REGISTER</span><h3>ZYNTH Trade instances</h3><p>One instance maps to one strategy. Timing is inherited; policy is instance-specific.</p></div><button className="approve" onClick={()=>setForm({name:"ZYNTH Trade #01",strategyId:strategies[0]?.id||"",status:"active",sourceMode:"validated_source",minReturnPct:-9,maxReturnPct:10,distribution:"balanced",decimalPlaces:2,weekendReporting:false,autoVerification:false})}><Plus size={13}/> New instance</button></div>
   {loading?<div className="admin-empty">Loading ZYNTH Trade…</div>:<div className="zt-list">{data.instances.map((x:any)=><article className="zt-row" key={x.id}><div className="zt-icon"><Bot size={16}/></div><div className="zt-main"><strong>{x.name}</strong><span>{x.strategy_name} · Validated source</span></div><span className={"trader-status-pill "+(x.status==="active"?"approved":"pending")}>{x.status}</span><div className="zt-policy"><b>{x.min_return_pct}% → {x.max_return_pct}%</b><small>{x.distribution} · {x.pending_runs||0} pending</small></div><button className="details" onClick={()=>setForm({...x,strategyId:x.strategy_id,minReturnPct:x.min_return_pct,maxReturnPct:x.max_return_pct,decimalPlaces:x.decimal_places,weekendReporting:x.weekend_reporting,autoVerification:x.auto_verification,sourceMode:x.source_mode})}>Configure</button></article>)}</div>}
  </div>
  <div className="zt-card"><div className="zt-head"><div><span className="muted">AUTOMATED RUN QUEUE</span><h3>Recent runs</h3></div><button className="details" onClick={load}><RefreshCw size={13}/> Refresh</button></div>
   <div className="zt-runs">{data.runs.map((r:any)=><div className="zt-run" key={r.id}><div><strong>{r.instance_name}</strong><span>{r.strategy_name} · {r.cycle_date}</span></div><div><b>{Number(r.generated_return_pct).toFixed(2)}%</b><span>{new Date(r.scheduled_at).toLocaleString("en-NG",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</span></div><span className={"trader-status-pill "+(r.status==="approved"?"approved":"pending")}>{r.status.replaceAll("_"," ")}</span>{r.status==="pending_verification"&&<div className="zt-actions"><button className="approve" disabled={!!busy} onClick={()=>verify(r.id,true)}><CheckCircle2 size={12}/> Approve</button><button className="reject" disabled={!!busy} onClick={()=>verify(r.id,false)}><XCircle size={12}/> Reject</button></div>}</div>)}</div>
  </div>
  {form&&<div className="trader-profile-backdrop" onClick={()=>setForm(null)}><aside className="trader-profile-drawer" onClick={e=>e.stopPropagation()}><button className="trader-drawer-close" onClick={()=>setForm(null)}>×</button><div className="trader-drawer-head"><div className="trader-avatar-large"><Bot size={18}/></div><div><span>ZYNTH TRADE CONFIGURATION</span><h3>{form.name}</h3><p>Existing reporting timing is inherited automatically.</p></div></div><div className="zt-form"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Strategy<select value={form.strategyId} onChange={e=>setForm({...form,strategyId:e.target.value})}>{strategies.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="paused">Paused</option><option value="disabled">Disabled</option></select></label><div className="zt-two"><label>Minimum return %<input type="number" step="0.01" value={form.minReturnPct} onChange={e=>setForm({...form,minReturnPct:Number(e.target.value)})}/></label><label>Maximum return %<input type="number" step="0.01" value={form.maxReturnPct} onChange={e=>setForm({...form,maxReturnPct:Number(e.target.value)})}/></label></div><label>Distribution<select value={form.distribution} onChange={e=>setForm({...form,distribution:e.target.value})}><option value="balanced">Balanced</option><option value="uniform">Uniform</option><option value="conservative">Conservative</option><option value="custom">Custom</option></select></label><label>Decimal places<input type="number" min="0" max="6" value={form.decimalPlaces} onChange={e=>setForm({...form,decimalPlaces:Number(e.target.value)})}/></label><label className="zt-check"><input type="checkbox" checked={form.weekendReporting} onChange={e=>setForm({...form,weekendReporting:e.target.checked})}/> Weekend reporting</label><label className="zt-check"><input type="checkbox" checked={form.autoVerification} onChange={e=>setForm({...form,autoVerification:e.target.checked})}/> Auto verification</label><div className="zt-warning"><ShieldCheck size={14}/><span>Approved ZYNTH Trade reports settle through the existing strategy NAV and investor accounting engine.</span></div><button className="approve zt-save" disabled={busy==="save"} onClick={save}>{busy==="save"?"Saving…":"Save ZYNTH Trade"} <CheckCircle2 size={13}/></button></div></aside></div>}
 </section>
}