"use client";
import{useEffect,useState}from"react";
import{Activity,AlertTriangle,ArrowDownLeft,ArrowLeftRight,ArrowUpRight,CheckCircle2,ChevronLeft,ChevronRight,Clock3,Download,Eye,Filter,RefreshCw,RotateCcw,Search,ShieldCheck,X,XCircle}from"lucide-react";
const money=(n:any,c="NGN")=>new Intl.NumberFormat("en-NG",{style:"currency",currency:c,minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0));
const dt=(v:any)=>v?new Date(v).toLocaleString("en-NG",{dateStyle:"medium",timeStyle:"short"}):"—";
const label=(s:any)=>String(s||"—").replaceAll("_"," ");
const tone=(s:string)=>({pending:"amber",processing:"blue",completed:"green",failed:"red",reversed:"gold",cancelled:"muted"}as any)[s]||"muted";
const types=[["","All types"],["deposit","Deposit"],["withdrawal","Withdrawal"],["investment","Investment"],["topup","Top-up"],["investment_redemption","Redemption"],["profit_unlock","Profit unlock"],["profit_withdrawal","Profit withdrawal"],["fee_deduction","Fee deduction"],["zpa_commission","ZPA commission"],["referral_reward","Referral reward"],["manual_adjustment","Manual adjustment"],["refund","Refund"],["reversal","Reversal"]];
const statuses=[["","All statuses"],["pending","Pending"],["processing","Processing"],["completed","Completed"],["failed","Failed"],["reversed","Reversed"],["cancelled","Cancelled"]];
export default function AdminTransactions(){
 const[rows,setRows]=useState<any[]>([]),[health,setHealth]=useState<any>({}),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[selected,setSelected]=useState(""),[detail,setDetail]=useState<any>(null),[detailLoading,setDetailLoading]=useState(false),[busy,setBusy]=useState("");
 const[q,setQ]=useState(""),[status,setStatus]=useState(""),[type,setType]=useState(""),[method,setMethod]=useState(""),[currency,setCurrency]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[min,setMin]=useState(""),[max,setMax]=useState(""),[filters,setFilters]=useState(false);const size=25;
 const qs=(extra:any={})=>{const p=new URLSearchParams(),v:any={search:q,status,type,method,currency,dateFrom:from,dateTo:to,minAmount:min,maxAmount:max,page,pageSize:size,...extra};Object.entries(v).forEach(([k,x])=>{if(x!==""&&x!=null)p.set(k,String(x))});return p};
 async function load(pg=page){setLoading(true);try{const r=await fetch("/api/admin/transactions?"+qs({page:pg}),{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.rows||[]);setTotal(Number(d.total||0));setHealth(d.health||{});setPage(pg)}catch(e){setNotice(e instanceof Error?e.message:"Unable to load transactions.")}finally{setLoading(false)}}
 useEffect(()=>{load(1)},[status,type,method,currency,from,to,min,max]); // eslint-disable-line react-hooks/exhaustive-deps
 async function open(id:string){setSelected(id);setDetail(null);setDetailLoading(true);try{const r=await fetch("/api/admin/transactions/"+id,{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error);setDetail(d)}catch(e){setNotice(e instanceof Error?e.message:"Unable to load transaction.");setSelected("")}finally{setDetailLoading(false)}}
 async function action(a:string){if(!selected)return;const reason=window.prompt("Reason for this action (saved permanently in the audit trail):")||"";if(reason.trim().length<5){setNotice("A reason of at least 5 characters is required.");return}if(["reverse","reject","return_pending"].includes(a)&&!window.confirm("This action changes financial state and is permanently audited. Continue?"))return;setBusy(a);try{const r=await fetch("/api/admin/transactions/action",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({transactionId:selected,action:a,reason:reason.trim()})}),d=await r.json();if(!r.ok)throw Error(d.error);setNotice("Transaction action completed.");await load(page);await open(selected)}catch(e){setNotice(e instanceof Error?e.message:"Transaction action failed.")}finally{setBusy("")}}
 const maxPage=Math.max(1,Math.ceil(total/size));
 return <section className="admin-transactions-page"><header className="admin-tx-header"><div><div className="eyebrow-row"><span className="eyebrow">ZYNTH / MONEY MOVEMENT</span><span className="live-dot"><i/> TRANSACTION CONTROL</span></div><h1>Transactions.</h1><p>The authoritative ledger for money movement, reconciliation and controlled overrides.</p></div><div className="admin-tx-actions"><button className="ghost" onClick={()=>load(page)} disabled={loading}><RefreshCw size={14}/>Refresh</button><a className="approve" href={"/api/admin/transactions?"+qs({page:1,pageSize:100,export:"csv"}).toString()}><Download size={14}/>Export CSV</a></div></header>
 {notice&&<div className="admin-notice"><AlertTriangle size={14}/><span>{notice}</span><button onClick={()=>setNotice("")}><X size={13}/></button></div>}
 <section className="admin-tx-health"><div><span>TODAY VOLUME</span><b>{money(health.today_volume)}</b><small>Completed volume</small></div><div><span>PENDING</span><b>{health.pending||0}</b><small>Awaiting resolution</small></div><div><span>PROCESSING</span><b>{health.processing||0}</b><small>Currently moving</small></div><div><span>FAILED / REVERSED</span><b>{Number(health.failed||0)+Number(health.reversed||0)}</b><small>{health.failed||0} failed · {health.reversed||0} reversed</small></div><div className={Number(health.provider_mismatches)?"alert":""}><span><Activity size={12}/> PROVIDER MISMATCH</span><b>{health.provider_mismatches||0}</b><small>NOWPayments vs ZYNTH</small></div><div className={Number(health.unmatched_provider_payments)?"alert":""}><span><AlertTriangle size={12}/> UNMATCHED</span><b>{health.unmatched_provider_payments||0}</b><small>Provider payments without ledger</small></div></section>
 <section className="admin-card admin-tx-card"><div className="admin-card-head"><div><span className="muted">MASTER LEDGER</span><h2>All transactions</h2><p>Search by ID, reference, user, payment reference or provider ID.</p></div><span className="admin-count">{total.toLocaleString()} records</span></div>
 <div className="admin-tx-toolbar"><label className="admin-tx-search"><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load(1)} placeholder="Search transactions…"/><button onClick={()=>load(1)}><Search size={13}/></button></label><button className="ghost" onClick={()=>setFilters(!filters)}><Filter size={14}/>Filters</button><button className="ghost" onClick={()=>{setQ("");setStatus("");setType("");setMethod("");setCurrency("");setFrom("");setTo("");setMin("");setMax("")}}><RotateCcw size={13}/>Reset</button></div>
 {filters&&<div className="admin-tx-filters"><label>STATUS<select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label>TYPE<select value={type} onChange={e=>setType(e.target.value)}>{types.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label>METHOD<input value={method} onChange={e=>setMethod(e.target.value)} placeholder="crypto / bank / manual"/></label><label>CURRENCY<input value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} placeholder="NGN"/></label><label>FROM<input type="date" value={from} onChange={e=>setFrom(e.target.value?e.target.value+"T00:00:00Z":"")}/></label><label>TO<input type="date" value={to} onChange={e=>setTo(e.target.value?e.target.value+"T00:00:00Z":"")}/></label><label>MIN<input value={min} onChange={e=>setMin(e.target.value)}/></label><label>MAX<input value={max} onChange={e=>setMax(e.target.value)}/></label></div>}
 <div className="admin-tx-table"><div className="admin-tx-head"><span>TRANSACTION</span><span>USER</span><span>TYPE / METHOD</span><span>AMOUNT</span><span>STATUS</span><span>DATE</span><span/></div>{loading?<div className="admin-empty"><RefreshCw size={20}/><p>Loading master ledger…</p></div>:rows.map(r=><button className="admin-tx-row" key={r.id} onClick={()=>open(r.id)}><div className="admin-tx-ref"><span>{r.direction==="debit"?<ArrowUpRight size={14}/>:<ArrowDownLeft size={14}/>}</span><span><b>{r.reference||r.id.slice(0,8)}</b><small>{r.id.slice(0,8)}…{r.provider_transaction_id?" · "+String(r.provider_transaction_id).slice(0,8)+"…":""}</small></span></div><div><b>{r.full_name||"Investor"}</b><small>{r.email||"—"}</small></div><div><b>{label(r.type)}</b><small>{r.method||r.source||"system"}{r.provider?" · "+r.provider:""}</small></div><div className={r.direction==="debit"?"debit":""}>{r.direction==="debit"?"−":"+"}{money(r.net_amount||r.amount,r.currency)}</div><div><span className={"admin-tx-status "+tone(r.status)}><i/>{label(r.status)}</span>{r.provider_status&&<small>Provider: {r.provider_status}</small>}</div><div><b>{new Date(r.created_at).toLocaleDateString("en-NG",{day:"2-digit",month:"short"})}</b><small>{new Date(r.created_at).toLocaleTimeString("en-NG",{hour:"2-digit",minute:"2-digit"})}</small></div><Eye size={14}/></button>)}{!loading&&!rows.length&&<div className="admin-empty"><Activity size={22}/><p>No transactions match the current filters.</p></div>}</div>
 <footer className="admin-tx-page"><span>{total?((page-1)*size+1):0}–{Math.min(page*size,total)} of {total}</span><div><button className="ghost" disabled={page<=1} onClick={()=>load(page-1)}><ChevronLeft size={13}/></button><b>{page} / {maxPage}</b><button className="ghost" disabled={page>=maxPage} onClick={()=>load(page+1)}><ChevronRight size={13}/></button></div></footer></section>
 {selected&&<div className="admin-tx-backdrop" onMouseDown={()=>setSelected("")}><aside className="admin-tx-drawer" onMouseDown={e=>e.stopPropagation()}>{detailLoading?<div className="admin-empty"><RefreshCw/><p>Loading transaction dossier…</p></div>:detail&&<><header><div><span className="muted">TRANSACTION DOSSIER</span><h2>{detail.transaction.reference||detail.transaction.id.slice(0,8)}</h2><p>{detail.transaction.id} · {dt(detail.transaction.created_at)}</p></div><button className="icon-button" onClick={()=>setSelected("")}><X size={17}/></button></header><div className={"admin-tx-detail-status "+tone(detail.transaction.status)}><b>{label(detail.transaction.status)}</b><span>{detail.transaction.provider_status?"Provider: "+detail.transaction.provider_status:"ZYNTH ledger state"}</span></div>
 <div className="admin-tx-hero"><div><span>NET AMOUNT</span><b>{detail.transaction.direction==="debit"?"−":"+"}{money(detail.transaction.net_amount||detail.transaction.amount,detail.transaction.currency)}</b><small>{detail.transaction.currency} · {label(detail.transaction.type)}</small></div><div><span>USER</span><b>{detail.user?.full_name||"Investor"}</b><small>{detail.user?.email||"—"}</small></div></div>
 <section className="admin-tx-section"><h3><ShieldCheck size={14}/> OVERVIEW</h3><div className="admin-tx-grid">{[["Transaction ID",detail.transaction.id],["Reference",detail.transaction.reference],["Type",label(detail.transaction.type)],["Method",detail.transaction.method||detail.transaction.metadata?.method||"—"],["Source",detail.transaction.source||detail.transaction.metadata?.source||"system"],["Created",dt(detail.transaction.created_at)],["Processed",dt(detail.transaction.processed_at)],["Processed by",detail.transaction.processed_by||"System"]].map(([a,b]:any)=><div key={a}><span>{a}</span><b className="break">{b||"—"}</b></div>)}</div></section>
 {detail.crypto_payment&&<section className="admin-tx-section"><h3><ArrowLeftRight size={14}/> PROVIDER / CRYPTO</h3><div className="admin-tx-grid">{[["Provider","NOWPayments"],["Payment ID",detail.crypto_payment.nowpayments_payment_id],["Order ID",detail.crypto_payment.order_id],["Pay currency",detail.crypto_payment.pay_currency],["Expected",String(detail.crypto_payment.pay_amount||"—")+" "+(detail.crypto_payment.pay_currency||"")],["Actually paid",String(detail.crypto_payment.actually_paid||"—")+" "+(detail.crypto_payment.actually_paid_currency||detail.crypto_payment.pay_currency||"")],["TX hash",detail.crypto_payment.transaction_hash],["Last IPN",dt(detail.crypto_payment.last_ipn_at)]].map(([a,b]:any)=><div key={a}><span>{a}</span><b className="break">{b||"—"}</b></div>)}</div></section>}
 {detail.deposit_request&&<section className="admin-tx-section"><h3><ArrowDownLeft size={14}/> DEPOSIT WORKFLOW</h3><div className="admin-tx-grid">{[["Status",detail.deposit_request.status],["Payment ref",detail.deposit_request.payment_reference],["Admin note",detail.deposit_request.admin_note],["Amount",money(detail.deposit_request.amount,detail.transaction.currency)]].map(([a,b]:any)=><div key={a}><span>{a}</span><b className="break">{b||"—"}</b></div>)}</div></section>}
 {detail.withdrawal_request&&<section className="admin-tx-section"><h3><ArrowUpRight size={14}/> WITHDRAWAL WORKFLOW</h3><div className="admin-tx-grid">{[["Status",detail.withdrawal_request.status],["Gross",money(detail.withdrawal_request.gross_amount,detail.withdrawal_request.currency)],["Fee",money(detail.withdrawal_request.fee_amount,detail.withdrawal_request.currency)],["Net",money(detail.withdrawal_request.net_amount,detail.withdrawal_request.currency)],["Bank",detail.withdrawal_request.bank_name],["Account","••••"+String(detail.withdrawal_request.account_number||"").slice(-4)]].map(([a,b]:any)=><div key={a}><span>{a}</span><b>{b||"—"}</b></div>)}</div></section>}
 <section className="admin-tx-section"><h3><ArrowLeftRight size={14}/> FINANCIAL IMPACT</h3><div className="admin-tx-impact"><div><span>BEFORE</span><b>{detail.transaction.balance_before!=null?money(detail.transaction.balance_before,detail.transaction.currency):"Not captured"}</b></div><i>→</i><div><span>TRANSACTION</span><b>{detail.transaction.direction==="debit"?"−":"+"}{money(detail.transaction.net_amount||detail.transaction.amount,detail.transaction.currency)}</b></div><i>→</i><div><span>AFTER</span><b>{detail.transaction.balance_after!=null?money(detail.transaction.balance_after,detail.transaction.currency):"Not captured"}</b></div></div></section>
 <section className="admin-tx-section"><h3><Clock3 size={14}/> TIMELINE</h3><div className="admin-tx-timeline">{(detail.timeline||[]).map((x:any,i:number)=><div key={i}><i/><span><b>{x.event}</b><small>{dt(x.at)} · {x.detail||""}</small></span></div>)}</div></section>
 <section className="admin-tx-section"><h3><ShieldCheck size={14}/> AUDIT TRAIL</h3><div className="admin-tx-audit">{(detail.audit||[]).map((a:any)=><div key={a.id}><b>{a.action}</b><small>{a.actor_name||"System"} · {dt(a.created_at)}</small>{a.metadata?.reason&&<p>{a.metadata.reason}</p>}</div>)}{!(detail.audit||[]).length&&<small>No audit entries yet.</small>}</div></section>
 <footer className="admin-tx-drawer-actions"><button className="ghost" onClick={()=>setSelected("")}>Close</button>{detail.transaction.can_approve&&<button className="approve" disabled={!!busy} onClick={()=>action("approve")}><CheckCircle2 size={14}/>Approve</button>}{detail.transaction.can_reject&&<button className="reject" disabled={!!busy} onClick={()=>action("reject")}><XCircle size={14}/>Reject</button>}{detail.transaction.can_return_pending&&<button className="ghost" disabled={!!busy} onClick={()=>action("return_pending")}><Clock3 size={14}/>Pending</button>}{detail.transaction.can_reverse&&<button className="reject" disabled={!!busy} onClick={()=>action("reverse")}><RotateCcw size={14}/>Reverse</button>}</footer></>}</aside></div>}
 </section>
}