"use client";
import {useEffect,useState} from "react";
import {CheckCircle2,Gift,RefreshCw,Settings2,Target,UsersRound,WalletCards} from "lucide-react";
const money=(n:any)=>`₦${Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export default function AdminZpa({refreshKey=0}:{refreshKey?:number}){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[selectedZpa,setSelectedZpa]=useState(""),[selectedInvestor,setSelectedInvestor]=useState("");
 const[settings,setSettings]=useState<any>({enabled:true,qualification_period_days:10,settlement_period_days:0,capital_incentive_rate:5}),[milestones,setMilestones]=useState<any[]>([]);
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/zpa",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load ZPA management.");setData(j);setSettings(j.settings);setMilestones(j.milestones||[])}catch(e){setMessage(e instanceof Error?e.message:"Unable to load ZPA management.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[refreshKey]);
 async function saveSettings(){setSaving(true);setMessage("");try{const r=await fetch("/api/admin/zpa",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"settings",...settings})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not save settings.");setSettings(j);setMessage("ZPA settings saved and audited.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save settings.")}finally{setSaving(false)}}
 async function saveMilestones(){setSaving(true);setMessage("");try{const r=await fetch("/api/admin/zpa",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"milestones",milestones})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not save milestones.");setMilestones(j);setMessage("Milestones saved. Existing earned milestones were not recalculated.");}catch(e){setMessage(e instanceof Error?e.message:"Could not save milestones.")}finally{setSaving(false)}}
 async function attribute(){if(!selectedZpa||!selectedInvestor)return;setSaving(true);setMessage("");try{const r=await fetch("/api/admin/zpa",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"attribute",zpa_id:selectedZpa,investor_id:selectedInvestor})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not attribute investor.");setMessage("Investor attributed. Qualification begins only after the first investment.");setSelectedInvestor("");await load();}catch(e){setMessage(e instanceof Error?e.message:"Could not attribute investor.")}finally{setSaving(false)}}
 if(loading)return <section className="admin-section"><div className="admin-card"><div className="trader-loading"><RefreshCw className="spin" size={18}/> Loading ZPA management…</div></div></section>;
 return <section className="admin-section">
  {message&&<div className="admin-notice">{message}</div>}
  <section className="admin-card zpa-program-card"><div className="admin-card-head"><div><span className="muted">ZPA PROGRAM</span><h2>Acquisition economics</h2><p>First qualifying investment only. Top-ups and recurring investments never generate new ZPA acquisition earnings.</p></div><span className="zpa-admin-live"><i/> Live configuration</span></div>
   <div className="admin-kpis"><div className="admin-kpi"><small>Active ZPAs</small><b>{(data.zpas||[]).length}</b></div><div className="admin-kpi"><small>Monthly thresholds</small><b>{milestones.length}</b></div><div className="admin-kpi"><small>Capital rate</small><b>{Number(settings.capital_incentive_rate||0)}%</b></div><div className="admin-kpi"><small>Qualification</small><b>{settings.qualification_period_days} days</b></div></div>
  </section>
  <section className="admin-card settings-card zpa-form-card"><div className="admin-card-head"><div><span className="muted">PROGRAM SETTINGS</span><h2>Rules & controls</h2><p>These rules govern new ZPA qualification and incentive calculations. Previously earned incentives are not recalculated.</p></div><span className="zpa-card-icon"><Settings2 size={17}/></span></div><div className="zpa-form-grid"><label className="zpa-field zpa-toggle-field"><span>Program status</span><small>Allow new ZPA acquisitions and qualification processing.</small><div className="zpa-toggle-row"><input type="checkbox" checked={!!settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/><b>{settings.enabled?"Program enabled":"Program paused"}</b></div></label><label className="zpa-field"><span>Qualification period</span><small>Days the first investment must remain qualified.</small><div className="zpa-input-wrap"><input type="number" min="1" max="365" value={settings.qualification_period_days} onChange={e=>setSettings({...settings,qualification_period_days:Number(e.target.value)})}/><em>days</em></div></label><label className="zpa-field"><span>Settlement period</span><small>Days between qualification and available earnings.</small><div className="zpa-input-wrap"><input type="number" min="0" max="365" value={settings.settlement_period_days} onChange={e=>setSettings({...settings,settlement_period_days:Number(e.target.value)})}/><em>days</em></div></label><label className="zpa-field"><span>Capital incentive</span><small>Percentage paid on the first qualifying investment only.</small><div className="zpa-input-wrap"><input type="number" min="0" max="100" step="0.01" value={settings.capital_incentive_rate} onChange={e=>setSettings({...settings,capital_incentive_rate:Number(e.target.value)})}/><em>%</em></div></label></div><div className="zpa-form-footer"><span>Changes are audited and apply to new qualifying activity.</span><button className="primary" disabled={saving} onClick={saveSettings}>{saving?"Saving…":"Save rules"}</button></div></section>
  <section className="admin-card zpa-form-card"><div className="admin-card-head"><div><span className="muted">MONTHLY MILESTONES</span><h2>Incremental rewards</h2><p>Rewards are additive: 50/80/120/150 produces ₦30k/₦50k/₦80k/₦120k cumulative.</p></div><span className="zpa-card-icon"><Gift size={17}/></span></div><div className="zpa-milestone-grid">{milestones.map((m,i)=><div className="zpa-milestone" key={m.id||i}><div><span>Milestone {i+1}</span><b>{m.threshold} qualified investors</b></div><label><span>Reward amount</span><div className="zpa-input-wrap"><span>₦</span><input type="number" min="0" value={m.reward_amount} onChange={e=>setMilestones(ms=>ms.map(x=>x===m?{...x,reward_amount:Number(e.target.value)}:x))}/></div></label><strong>+{money(m.reward_amount)}</strong></div>)}</div><div className="zpa-form-footer"><span>Existing earned milestones remain unchanged.</span><button className="primary" disabled={saving} onClick={saveMilestones}>{saving?"Saving…":"Save milestones"}</button></div></section>
  <section className="admin-card"><div className="admin-card-head"><div><span className="muted">ZPA DIRECTORY</span><h2>Performance</h2></div><UsersRound size={18}/></div><div className="admin-table">{(data.zpas||[]).map((z:any)=><div className="admin-row" key={z.id}><div className="admin-person"><span className="avatar"><Target size={14}/></span><span><b>{z.full_name||"Unnamed ZPA"}</b><small>{z.email||z.id} · {z.account_status}</small></span></div><span>{z.qualified_count} qualified</span><span>{money(z.capital_acquired)} capital</span><span>{money(z.available)} available</span><strong>{money(z.total_earned)} earned</strong></div>)}</div></section>
  <section className="admin-card zpa-form-card"><div className="admin-card-head"><div><span className="muted">CONTROLLED ATTRIBUTION</span><h2>Assign investor to ZPA</h2><p>Use only for legitimate acquisition disputes or offline acquisition records. The investor must not have invested yet.</p></div><span className="zpa-card-icon"><WalletCards size={17}/></span></div><div className="zpa-form-grid zpa-attribution-grid"><label className="zpa-field"><span>ZPA partner</span><small>Choose the acquisition partner receiving attribution.</small><select value={selectedZpa} onChange={e=>setSelectedZpa(e.target.value)}><option value="">Select ZPA</option>{(data.zpas||[]).map((z:any)=><option key={z.id} value={z.id}>{z.full_name||z.email}</option>)}</select></label><label className="zpa-field"><span>Eligible investor</span><small>Only investors with no prior investment or attribution appear.</small><select value={selectedInvestor} onChange={e=>setSelectedInvestor(e.target.value)}><option value="">Select eligible investor</option>{(data.attribution_candidates||[]).map((u:any)=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></label></div><div className="zpa-form-footer"><span>Attribution is permanent unless an administrator reassigns it for a documented dispute.</span><button className="primary" disabled={saving||!selectedZpa||!selectedInvestor} onClick={attribute}>{saving?"Saving…":"Create attribution"}</button></div></section>
  <section className="admin-card"><div className="admin-card-head"><div><span className="muted">RECENT INCENTIVES</span><h2>Ledger</h2></div><CheckCircle2 size={18}/></div><div className="admin-table">{(data.recent_earnings||[]).map((e:any)=><div className="admin-row" key={e.id}><div className="admin-person"><span className="avatar">{e.earning_type==="milestone"?<Gift size={14}/>:<Target size={14}/>}</span><span><b>{e.zpa_name}</b><small>{e.earning_type.replaceAll("_"," ")} · {e.status}</small></span></div><span>{e.investor_name}</span><strong>{money(e.amount)}</strong></div>)}</div></section>
 </section>
}
