"use client";
import {useEffect,useState} from "react";
type Rule={rule_key:string;name:string;description?:string;enabled:boolean;points:number;threshold_count:number;window_minutes:number;action:string};
const money=(n:any)=>"₦"+Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});
const sections=[["overview","Risk Overview"],["critical","Critical"],["high","High"],["medium","Medium"],["low","Low"],["aml_alerts","AML Alerts"],["kyc_reviews","KYC Reviews"],["suspicious_users","Suspicious Users"],["device_clusters","Device Clusters"],["bank_clusters","Bank Clusters"],["crypto_clusters","Crypto Address Clusters"],["referral_fraud","Referral Fraud"],["zpa_fraud","ZPA Fraud"],["account_takeover","Account Takeover"],["withdrawal_risk","Withdrawal Risk"]] as const;
export default function AdminRisk(){
 const[d,setD]=useState<any>({overview:{}}),[loading,setLoading]=useState(true),[section,setSection]=useState("overview"),[saving,setSaving]=useState(""),[notice,setNotice]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/risk?limit=100",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load Risk & Compliance.");setD(j)}catch(e){setNotice(e instanceof Error?e.message:"Unable to load Risk & Compliance.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function resolve(id:string,status:string,action:string){const r=await fetch("/api/admin/risk",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"resolve",caseId:id,status,riskAction:action,note:"Admin Risk & Compliance review"})});const j=await r.json();setNotice(r.ok?"Risk case updated.":j.error||"Risk action failed.");if(r.ok)await load()}
 async function saveRule(rule:Rule){setSaving(rule.rule_key);const r=await fetch("/api/admin/risk",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"update_rule",ruleKey:rule.rule_key,enabled:rule.enabled,points:rule.points,thresholdCount:rule.threshold_count,windowMinutes:rule.window_minutes,riskAction:rule.action})});const j=await r.json();setNotice(r.ok?"Risk rule updated.":j.error||"Could not update rule.");setSaving("");if(r.ok)await load()}
 const o=d.overview||{}, rows=section==="overview"?[]:(d[section]||[]);
 const card=(title:string,children:any)=><section className="admin-card"><div className="admin-card-head"><div><span className="muted">RISK & COMPLIANCE</span><h2>{title}</h2><p>Signals are evidence for review. Shared IP alone is never an automatic lock.</p></div></div>{children}</section>;
 return <section className="admin-section">
  <div className="admin-kpi-grid">
   {["critical","high","medium","low"].map(k=><button key={k} className="admin-kpi" onClick={()=>setSection(k)}><span>{k.toUpperCase()}</span><b>{o[k]||0}</b></button>)}
   <button className="admin-kpi" onClick={()=>setSection("aml_alerts")}><span>AML ALERTS</span><b>{o.aml_alerts||0}</b></button>
   <button className="admin-kpi" onClick={()=>setSection("withdrawal_risk")}><span>WITHDRAWAL RISK</span><b>{o.withdrawal_risk||0}</b></button>
  </div>
  {notice&&<div className="admin-notice">{notice}</div>}
  <div className="admin-filter" style={{display:"flex",flexWrap:"wrap",gap:7,marginBottom:14}}>{sections.map(([k,l])=><button key={k} className={section===k?"admin-filter active":"admin-filter"} onClick={()=>setSection(k)}>{l}</button>)}</div>
  {loading?<div className="admin-card admin-empty">Loading Risk & Compliance…</div>:section==="overview"?<div className="referral-admin-grid">
   {card("Risk overview",<div className="admin-table">{sections.slice(1).map(([k,l])=><div className="admin-row" key={k}><span><b>{l}</b></span><strong>{k==="critical"?o.critical:k==="high"?o.high:k==="medium"?o.medium:k==="low"?o.low:o[k]||0}</strong><button className="ghost" onClick={()=>setSection(k)}>Open</button></div>)}</div>)}
   {card("Open cases",<div className="admin-table">{(d.critical||[]).concat(d.high||[]).slice(0,20).map((x:any)=><div className="admin-row" key={x.case_id||x.user_id}><span><b>{x.full_name||x.email}</b><small>{x.email}</small></span><span>{x.classification} · {x.score}/100</span><span>{x.reason||"Automated risk assessment"}</span><button className="ghost" onClick={()=>x.case_id&&resolve(x.case_id,"IN_REVIEW","MONITOR")}>Review</button></div>)}</div>)}
  </div>:section==="critical"||section==="high"?card(section.toUpperCase()+" cases",<div className="admin-table">{rows.length?rows.map((x:any)=><div className="admin-row" key={x.case_id||x.user_id}><span><b>{x.full_name||x.email||x.user_id}</b><small>{x.email}</small></span><span>{x.classification} · {x.score}/100</span><span>{x.reason||"Risk case"}</span>{x.case_id?<div className="row-actions"><button className="ghost" onClick={()=>resolve(x.case_id,"IN_REVIEW","MONITOR")}>Review</button><button className="ghost" onClick={()=>resolve(x.case_id,"RESOLVED","NONE")}>Clear</button></div>:null}</div>):<div className="admin-empty">No {section} cases.</div>}</div>):section==="medium"||section==="low"?card(section.toUpperCase()+" users",<div className="admin-table">{rows.length?rows.map((x:any)=><div className="admin-row" key={x.user_id}><span><b>{x.full_name||x.email}</b><small>{x.email}</small></span><strong>{x.score}/100</strong><span>{x.classification}</span></div>):<div className="admin-empty">No {section} users.</div>}</div>):card(sections.find(x=>x[0]===section)?.[1]||section,<div className="admin-table">{rows.length?rows.map((x:any,i:number)=><div className="admin-row" key={x.id||x.user_id||x.cluster_key||x.zpa_id||x.referrer_id||i}><div className="admin-person"><span className="avatar">R</span><span><b>{x.full_name||x.referrer_name||x.zpa_name||x.address_masked||x.bank_name||"Risk signal"}</b><small>{x.email||x.cluster_key||x.flag_type||x.status||""}</small></span></div><span>{x.score!==undefined?x.score+"/100":x.risk_score!==undefined?"Risk "+x.risk_score:""}</span><span>{x.user_count?x.user_count+" users":x.referral_count?x.referral_count+" referrals":x.acquisition_count?x.acquisition_count+" acquisitions":x.gross_amount?money(x.gross_amount):x.description||""}</span><strong>{x.classification||x.severity||x.action||""}</strong></div>):<div className="admin-empty">No active signals in this section.</div>}</div>)}
  {section==="overview"&&<section className="admin-card" style={{marginTop:14}}><div className="admin-card-head"><div><span className="muted">POLICY ENGINE</span><h2>Central risk rules</h2><p>One risk engine powers behavioural, referral, ZPA and withdrawal controls.</p></div></div><div className="admin-table">{(d.rules||[]).map((r:Rule)=><div className="admin-row" key={r.rule_key}><div className="admin-person"><span className="avatar">R</span><span><b>{r.name||r.rule_key}</b><small>{r.rule_key} · {r.description||"Configured signal"}</small></span></div><label><input type="checkbox" checked={r.enabled} onChange={e=>setD((x:any)=>({...x,rules:(x.rules||[]).map((q:Rule)=>q.rule_key===r.rule_key?{...q,enabled:e.target.checked}:q)}))}/> Enabled</label><label>Points <input style={{width:65}} type="number" min={0} max={100} value={r.points} onChange={e=>setD((x:any)=>({...x,rules:(x.rules||[]).map((q:Rule)=>q.rule_key===r.rule_key?{...q,points:Number(e.target.value)}:q)}))}/></label><button className="approve" disabled={saving===r.rule_key} onClick={()=>saveRule(r)}>{saving===r.rule_key?"Saving…":"Save"}</button></div>)}</div></section>}
 </section>
}