"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {Activity,ArrowDownToLine,ArrowDownLeft,ArrowUpRight,ArrowLeftRight,BarChart3,Bell,CheckCircle2,ChevronRight,Clock3,Copy,ExternalLink,Eye,RefreshCw,Settings2,ShieldCheck,TrendingUp,Users,Target,X,XCircle,Pencil,Pause,Play,Archive,Trash2,Gift,Headphones,LogOut,Send} from "lucide-react";
import AdminUsers from "@/components/admin-users";
import AdminKyc from "@/components/admin-kyc";
import ThemeSwitcher from "@/components/theme-switcher";
import AdminInvestmentSettings from "@/components/admin-investment-settings";
import AdminStrategyForm from "@/components/admin-strategy-form";
import AdminTraders from "@/components/admin-traders";
import AdminNotificationCenter from "@/components/admin-notification-center";
import AdminBroadcastCenter from "@/components/admin-broadcast-center";
import AdminNotificationBell from "@/components/admin-notification-bell";
import AdminPushPrompt from "@/components/admin-push-prompt";
import AdminReferralCenter from "@/components/admin-referral-center";
import AdminSupportCenter from "@/components/admin-support-center";
import AdminTraderGovernance from "@/components/admin-trader-governance";
import AdminZpa from "@/components/admin-zpa";
import AdminTransactions from "@/components/admin-transactions";

const money=(n:any)=>`₦${Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const pct=(n:any)=>`${Number(n||0).toFixed(2)}%`;

export default function AdminPanel({initialData,adminEmail}:{initialData:any;adminEmail:string}){
 const[data,setData]=useState(initialData||{}),[tab,setTab]=useState("overview"),[refreshing,setRefreshing]=useState(false),[refreshKey,setRefreshKey]=useState(0),[moneyOpen,setMoneyOpen]=useState(false),[reports,setReports]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]),[strategies,setStrategies]=useState<any[]>([]),[traders,setTraders]=useState<any[]>([]),[editingStrategy,setEditingStrategy]=useState<any>(null),[notificationTemplates,setNotificationTemplates]=useState<any[]>([]),[busy,setBusy]=useState(""),[notice,setNotice]=useState(""),[preview,setPreview]=useState<any>(null),[previewBusy,setPreviewBusy]=useState(""),[mt5Loading,setMt5Loading]=useState(false),[mt5CopyState,setMt5CopyState]=useState("");
 async function load(){const [q,s,t,n,support]=await Promise.all([fetch("/api/admin/settlements").then(r=>r.json()),fetch("/api/admin/strategies").then(r=>r.json()),fetch("/api/admin/traders").then(r=>r.json()),fetch("/api/admin/notification-templates").then(r=>r.json()),fetch("/api/admin/support").then(r=>r.ok?r.json():{tickets:[]}).catch(()=>({tickets:[]}))]);const supportUnread=Number(support.attention_count||0);setReports(q.reports||[]);setHistory(q.history||[]);setStrategies(s.strategies||[]);setTraders(t.traders||[]);setNotificationTemplates(n.templates||[]);setData((x:any)=>({...x,support_unread_count:supportUnread,mt5_pending_count:Number(t.mt5_pending_count||0),pending_reports:(q.pending_reports??x.pending_reports),pending_report_queue:(q.pending_report_queue??x.pending_report_queue),strategies:(s.strategies?.length??x.strategies),traders:(t.traders?.length??x.traders)}))}
 async function refreshData(){setRefreshing(true);setNotice("");try{await load();setRefreshKey(x=>x+1);setNotice("Admin data refreshed.");window.setTimeout(()=>setNotice(""),3000)}catch(e){setNotice(e instanceof Error?e.message:"Could not refresh admin data.")}finally{setRefreshing(false)}}
 useEffect(()=>{load();const timer=window.setInterval(async()=>{try{const r=await fetch("/api/admin/support",{cache:"no-store"});if(!r.ok)return;const j=await r.json();setData((x:any)=>({...x,support_unread_count:Number(j.attention_count||0)}))}catch{}} ,15000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{const handler=()=>setTab("notifications");window.addEventListener("zynth-admin-open-notifications",handler);return()=>window.removeEventListener("zynth-admin-open-notifications",handler)},[]);
 async function act(id:string,a:string){setBusy(id);setNotice("");let reason="";if(a==="reject")reason=window.prompt("Reason for rejection")||"Report rejected";const r=await fetch("/api/admin/settlements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reportId:id,action:a,reason})});const j=await r.json();setNotice(r.ok?(a==="confirm"?"Settlement confirmed and investor NAV updated.":"Report rejected."):(j.error||"Action failed."));await load();setBusy("")}
 async function openPreview(id:string){setPreviewBusy(id);setNotice("");const r=await fetch("/api/admin/settlements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reportId:id,action:"preview"})});const j=await r.json();if(!r.ok)setNotice(j.error||"Could not load settlement preview.");else setPreview(j);setPreviewBusy("")}
 const closePreview=()=>setPreview(null);
 return <div className="admin-frame">
  <aside className="admin-sidebar"><Link href="/dashboard" className="admin-brand"><span className="brand-mark">Z</span><span>ZYNTH</span><small>ADMIN</small></Link><div className="admin-nav-label">CONTROL CENTER</div><nav className="admin-list-nav">
   {[{k:"overview",l:"Overview",i:BarChart3,b:data.pending_reports},{k:"settlements",l:"Settlements",i:Clock3,b:data.pending_reports},{k:"strategies",l:"Strategies",i:TrendingUp,b:data.strategies},{k:"investors",l:"Investors",i:Users,b:data.investors},{k:"kyc",l:"KYC & AML",i:ShieldCheck,b:0},{k:"traders",l:"Traders",i:ShieldCheck,b:data.mt5_pending_count||0},{k:"trader-governance",l:"Trader Governance",i:ShieldCheck,b:0},{k:"notifications",l:"Notifications",i:Bell,b:0},{k:"broadcasts",l:"Messaging Broadcast",i:Send,b:0},{k:"support",l:"Customer Service",i:Headphones,b:Number(data.support_unread_count||0)},{k:"referrals",l:"Referrals",i:Gift,b:0},{k:"zpa",l:"ZPA",i:Target,b:0}].map(({k,l,i:Icon,b})=><button key={k} className={tab===k?"admin-list-item active":"admin-list-item"} onClick={()=>setTab(k)}><span className="admin-list-icon"><Icon size={16}/></span><span className="admin-list-label">{l}</span>{b>0&&<em>{b}</em>}</button>)}
   <div className={"admin-money-nav "+(moneyOpen||["deposits","withdrawals","redemptions","transactions"].includes(tab)?"open":"")}><button className={["deposits","withdrawals","redemptions","transactions"].includes(tab)?"admin-list-item active":"admin-list-item"} onClick={()=>setMoneyOpen(v=>!v)}><span className="admin-list-icon"><ArrowLeftRight size={16}/></span><span className="admin-list-label">Money Movement</span><span className="admin-money-meta">FLOW</span><ChevronRight size={13}/></button>{moneyOpen&&<div className="admin-money-subnav"><button onClick={()=>{setTab("deposits");setMoneyOpen(false)}}>Deposits</button><button onClick={()=>{setTab("withdrawals");setMoneyOpen(false)}}>Withdrawals</button><button onClick={()=>{setTab("redemptions");setMoneyOpen(false)}}>Redemptions</button><button onClick={()=>{setTab("transactions");setMoneyOpen(false)}}>Transactions</button></div>}</div>
   <button className={tab==="settings"?"admin-list-item active":"admin-list-item"} onClick={()=>setTab("settings")}><span className="admin-list-icon"><Settings2 size={16}/></span><span className="admin-list-label">Settings</span></button>
  </nav><div className="admin-sidebar-bottom"><span className="admin-session"><i/>Online</span><div className="admin-identity"><span className="avatar">A</span><span><b>Administrator</b><small>{adminEmail}</small></span></div></div></aside>
  <main className="admin-main"><header className="admin-topbar"><div><div className="eyebrow-row"><span className="eyebrow">ZYNTH / ADMIN</span><span className="live-dot"><i/> CONTROL ONLINE</span></div><h1>{tab==="overview"?"Control center":tab==="kyc"?"KYC & AML":tab.charAt(0).toUpperCase()+tab.slice(1)}</h1><p>Portfolio operations, investor controls and compliance review.</p></div><div className="admin-top-actions"><AdminNotificationBell/><ThemeSwitcher/><button className="ghost admin-refresh" onClick={refreshData} disabled={refreshing}><RefreshCw size={15}/> {refreshing?"Refreshing…":"Refresh data"}</button></div></header>{notice&&<div className="admin-notice">{notice}</div>}<AdminPushPrompt/>
   {tab==="kyc"&&<section className="admin-section"><AdminKyc/></section>}
   {tab==="transactions"&&<section className="admin-section"><AdminTransactions/></section>}
   {tab==="investors"&&<section className="admin-section"><section className="admin-card admin-users-card"><div className="admin-card-head"><div><span className="muted">INVESTOR DIRECTORY</span><h2>Investors</h2><p>Account status and portfolio controls.</p></div></div><AdminUsers initialUsers={[]} refreshKey={refreshKey}/></section></section>}
   {tab==="overview"&&<section className="admin-section"><div className="admin-kpis">{[[TrendingUp,"AUM",money(data.aumm),"PORTFOLIO","investors"],[Users,"Investors",data.investors,"ACCOUNTS","investors"],[ShieldCheck,"Traders",data.traders,"OPERATORS","traders"],[Clock3,"Pending reports",data.pending_reports,"ACTION","settlements"],[ArrowDownToLine,"Withdrawals",data.withdrawals_pending,"ACTION","withdrawals"],[ArrowDownLeft,"Pending deposits",data.pending_deposits,"ACTION","deposits"],[ArrowLeftRight,"Pending redemptions",data.pending_redemptions,"ACTION","redemptions"]].map(([Icon,label,val,tag,target]:any)=><div className={"admin-kpi"+(target?" admin-kpi-clickable":"")} key={label} onClick={()=>target&&setTab(target)}><div className="admin-kpi-top"><span className="admin-kpi-icon"><Icon size={16}/></span><em>{tag}</em></div><small>{label}</small><b>{val}</b></div>)}</div></section>}
   {tab==="traders"&&<AdminTraders onSaved={load} refreshKey={refreshKey}/>} {tab==="trader-governance"&&<AdminTraderGovernance/>}{tab==="zpa"&&<AdminZpa refreshKey={refreshKey}/>} {tab==="notifications"&&<AdminNotificationCenter initialTemplates={notificationTemplates} refreshKey={refreshKey}/>} {tab==="broadcasts"&&<AdminBroadcastCenter/>}{tab==="support"&&<AdminSupportCenter refreshKey={refreshKey}/>} {tab==="referrals"&&<AdminReferralCenter refreshKey={refreshKey}/>}
   {tab==="strategies"&&<section className="admin-section"><AdminStrategyForm traders={traders} editStrategy={editingStrategy} onCancel={()=>setEditingStrategy(null)} onSaved={()=>{setEditingStrategy(null);load()}}/></section>}
   {tab==="deposits"&&<section className="admin-section"><Link className="text-action" href="/admin/deposits">Open deposit queue <ChevronRight size={13}/></Link></section>}
   {tab==="withdrawals"&&<section className="admin-section"><Link className="text-action" href="/admin/withdrawals">Open withdrawal queue <ChevronRight size={13}/></Link></section>}
   {tab==="redemptions"&&<section className="admin-section"><Link className="text-action" href="/admin/redemptions">Open redemption control <ChevronRight size={13}/></Link></section>}
   {tab==="settings"&&<section className="admin-section"><AdminInvestmentSettings refreshKey={refreshKey}/></section>}
  </main></div>
}