"use client";
import {useEffect,useState} from "react";
import {AlertTriangle,CheckCircle2,Clock3,Eye,FileText,Pencil,Save,ShieldAlert} from "lucide-react";
import {RenderRules} from "@/components/trader-rules-view";
export default function AdminTraderGovernance(){const[data,setData]=useState<any>({rules:[],actions:[],traders:[],acknowledgements:[]});const[loading,setLoading]=useState(true);const[tab,setTab]=useState("policy");const[preview,setPreview]=useState(false);const[editor,setEditor]=useState<any>(null);const[reason,setReason]=useState("");const[traderId,setTraderId]=useState("");const[severity,setSeverity]=useState("medium");const[type,setType]=useState("warning");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
async function load(){setLoading(true);const r=await fetch("/api/admin/trader-governance",{cache:"no-store"});const j=await r.json();setData(j);if(!editor&&j.rules?.length){const published=j.rules.find((x:any)=>x.status==="published");setEditor(published||j.rules[0])}setLoading(false)}useEffect(()=>{load()},[]);
async function save(action:string){if(!editor?.content?.trim())return;setBusy(true);const r=await fetch("/api/admin/trader-governance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,title:editor.title,content:editor.content,requiresReacknowledgement:editor.requires_reacknowledgement!==false})});const j=await r.json();setNotice(r.ok?(action==="publish_rule"?"Rules published. Traders may be required to re-acknowledge the new version.":"Draft saved."):j.error||"Save failed.");if(r.ok){setEditor(j.rule);await load()}setBusy(false)}
async function discipline(){if(!traderId||!reason.trim())return;setBusy(true);const r=await fetch("/api/admin/trader-governance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"disciplinary",traderId,type,severity,reason})});const j=await r.json();setNotice(r.ok?(j.terminated?"Third warning threshold reached — trader terminated and Trader Desk restricted.":"Disciplinary action recorded."):(j.error||"Action failed."));if(r.ok){setReason("");await load()}setBusy(false)}
if(loading)return <section className="admin-section"><div className="admin-card"><div className="admin-empty"><Clock3 size={20}/>Loading Trader Governance…</div></div></section>;
const published=data.rules?.find((x:any)=>x.status==="published");const acknowledgements=(data.acknowledgements||[]).filter((x:any)=>x.document_id===published?.id);
return <section className="admin-section admin-governance">
 <div className="admin-governance-tabs"><button className={tab==="policy"?"active":""} onClick={()=>setTab("policy")}><FileText size={14}/> Rules & Standards</button><button className={tab==="discipline"?"active":""} onClick={()=>setTab("discipline")}><ShieldAlert size={14}/> Discipline</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}><Clock3 size={14}/> Version history</button></div>
 {notice&&<div className="admin-notice">{notice}</div>}
 {tab==="policy"&&<div className="admin-governance-grid"><section className="admin-card"><div className="admin-card-head"><div><span className="muted">POLICY EDITOR</span><h2>Edit Rules & Standards</h2><p>Edit it like a blog post. Publishing creates a new immutable version.</p></div><span className="admin-count">v{published?.version||1}</span></div><label className="gov-label">Title<input value={editor?.title||""} onChange={e=>setEditor({...editor,title:e.target.value})}/></label><div className="gov-editor-mode"><button className={!preview?"active":""} onClick={()=>setPreview(false)}><Pencil size={13}/> Edit</button><button className={preview?"active":""} onClick={()=>setPreview(true)}><Eye size={13}/> Preview</button></div>{preview?<div className="gov-preview"><RenderRules text={editor?.content||""}/></div>:<label className="gov-label">Content<textarea className="gov-editor" value={editor?.content||""} onChange={e=>setEditor({...editor,content:e.target.value})}/></label>}<div className="gov-editor-help">Markdown-style headings and lists are supported. Use <b>#</b>, <b>##</b>, <b>###</b> and <b>-</b> for structure.</div><label className="gov-check"><input type="checkbox" checked={editor?.requires_reacknowledgement!==false} onChange={e=>setEditor({...editor,requires_reacknowledgement:e.target.checked})}/> Require trader acknowledgement for this published version</label><div className="gov-actions"><button className="ghost" disabled={busy} onClick={()=>save("save_draft")}><Save size={14}/> Save draft</button><button className="primary" disabled={busy} onClick={()=>save("publish_rule")}><CheckCircle2 size={14}/> Publish update</button></div></section><aside className="admin-card"><div className="admin-card-head"><div><span className="muted">ACKNOWLEDGEMENT</span><h2>Current version</h2><p>Track who has accepted the current published policy.</p></div></div><div className="gov-stat"><strong>{acknowledgements.length}</strong><span>acknowledged</span></div><div className="gov-trader-list">{(data.traders||[]).map((t:any)=>{const ok=acknowledgements.some((a:any)=>a.trader_id===t.user_id);return <div key={t.user_id}><span><b>{t.display_name||t.full_name||t.email||"Trader"}</b><small>{t.email||""} · {Number(t.missed_reports||0)} missed reports this month</small></span><em className={ok?"ok":"pending"}>{ok?"Acknowledged":"Pending"}</em></div>})}</div></aside></div>}
 {tab==="discipline"&&<div className="admin-governance-grid"><section className="admin-card"><div className="admin-card-head"><div><span className="muted">DISCIPLINARY CONTROL</span><h2>Issue action</h2><p>Warnings are cumulative. The third active formal warning triggers termination and Trader Desk restriction.</p></div></div><label className="gov-label">Trader<select value={traderId} onChange={e=>setTraderId(e.target.value)}><option value="">Select trader</option>{(data.traders||[]).map((t:any)=><option key={t.user_id} value={t.user_id}>{t.display_name||t.full_name||t.email}</option>)}</select></label><div className="gov-form-grid"><label className="gov-label">Action<select value={type} onChange={e=>setType(e.target.value)}><option value="warning">Warning</option><option value="suspension">Suspend</option><option value="termination">Terminate</option><option value="reinstatement">Reinstate</option><option value="note">Note</option></select></label><label className="gov-label">Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label></div><label className="gov-label">Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Describe the violation and required corrective action."/></label><button className="primary" disabled={busy||!traderId||!reason.trim()} onClick={discipline}><AlertTriangle size={14}/> Record action</button></section><section className="admin-card"><div className="admin-card-head"><div><span className="muted">RECENT ACTIONS</span><h2>Disciplinary history</h2></div></div><div className="gov-action-list">{(data.actions||[]).map((a:any)=><div key={a.id}><span className={a.severity==="critical"?"critical":a.action_type==="warning"?"warning":"neutral"}>{a.action_type==="warning"?"Warning "+(a.warning_number||""):a.action_type}</span><b>{a.reason}</b><small>{new Date(a.created_at).toLocaleDateString("en-NG")} · {a.severity}</small></div>)}{!data.actions?.length&&<div className="admin-empty"><CheckCircle2 size={18}/> No disciplinary actions.</div>}</div></section></div>}
 {tab==="history"&&<section className="admin-card"><div className="admin-card-head"><div><span className="muted">POLICY ARCHIVE</span><h2>Version history</h2><p>Published versions remain available for audit.</p></div></div><div className="gov-history">{(data.rules||[]).map((r:any)=><button key={r.id} onClick={()=>{setEditor(r);setTab("policy")}}><span><b>Version {r.version}</b><small>{r.status} · {r.published_at?new Date(r.published_at).toLocaleDateString("en-NG"):"draft"}</small></span><Pencil size={14}/></button>)}</div></section>}
 </section>}
