"use client";
import {useEffect,useState} from "react";
import {CheckCircle2,Clock3,RefreshCw,XCircle,Zap,WalletCards} from "lucide-react";
const money=(n:any)=>"₦"+Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});
const dt=(v:any)=>v?new Date(v).toLocaleString("en-NG",{dateStyle:"medium",timeStyle:"short"}):"—";
const statusLabel=(s:string)=>({pending:"Awaiting review",approved:"Approved · waiting release",processing:"Processing",released:"Released",rejected:"Rejected",cancelled:"Cancelled"}[s]||s);
export default function AdminRedemptions(){
 const[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(""),[notice,setNotice]=useState("");
 async function load(){const r=await fetch("/api/admin/redemptions");const d=await r.json();if(r.ok)setRows(d.redemptions||[]);else setNotice(d.error||"Unable to load redemptions.");}
 useEffect(()=>{load()},[]);
 async function act(id:string,action:string){setBusy(id);setNotice("");let reason="";if(action==="reject")reason=window.prompt("Reason for rejecting this redemption:")||"Redemption rejected";const r=await fetch("/api/admin/redemptions/action",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({redemptionId:id,action,reason})});const d=await r.json();setNotice(r.ok?"Redemption action completed.":(d.error||"Action failed."));await load();setBusy("");}
 return <section className="admin-section"><header className="admin-topbar"><div><div className="eyebrow-row"><span className="eyebrow">ZYNTH / ADMIN</span><span className="live-dot"><i/> LIQUIDITY CONTROL</span></div><h1>Investment redemptions</h1><p>Approve, monitor and release investor exits without touching strategy accounting manually.</p></div><button className="ghost admin-refresh" onClick={load}><RefreshCw size={15}/> Refresh</button></header>{notice&&<div className="admin-notice">{notice}</div>}<section className="admin-card"><div className="admin-card-head"><div><span className="muted">REDEMPTION QUEUE</span><h2>Investor exits</h2><p>Units are reserved at the confirmed NAV when requested. Cash is released only after the configured window.</p></div><span className="admin-count">{rows.filter(r=>["pending","approved","processing"].includes(r.status)).length} active</span></div><div className="admin-table">{rows.map(r=><div className="admin-row settlement-row" key={r.id}><div className="admin-person"><span className="avatar"><WalletCards size={14}/></span><span><b>{r.full_name||r.email||"Investor"}</b><small>{r.strategy_name} · {r.reference}</small><small>Requested {dt(r.requested_at)}</small></span></div><span><b>{money(r.gross_amount)}</b><small>Gross</small></span><span><b>{money(r.net_amount)}</b><small>Net · fee {money(r.fee_amount)}</small></span><span><b>NAV {Number(r.nav||0).toFixed(4)}</b><small>{Number(r.requested_units||0).toFixed(6)} units</small></span><span className={"status-text "+r.status}>{statusLabel(r.status)}<small>{r.release_at?"Release "+dt(r.release_at):""}</small></span><div className="row-actions">{r.status==="pending"&&<><button className="approve" disabled={busy===r.id} onClick={()=>act(r.id,"approve")}><CheckCircle2 size={14}/> Approve</button><button className="reject" disabled={busy===r.id} onClick={()=>act(r.id,"reject")}><XCircle size={14}/> Reject</button></>}{r.status==="approved"&&<button className="details" disabled={busy===r.id} onClick={()=>act(r.id,"processing")}><Clock3 size={14}/> Processing</button>}{r.status==="processing"&&<button className="approve" disabled={busy===r.id} onClick={()=>act(r.id,"release")}><Zap size={14}/> Release now</button>}</div></div>)}{!rows.length&&<div className="admin-empty"><Clock3 size={22}/><p>No redemption requests yet.</p></div>}</div></section></section>
}