"use client";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, CircleDollarSign, FileText, Plus, ShieldCheck, Sparkles, UserRound, X } from "lucide-react";

export default function AdminStrategyForm({ traders, onSaved, editStrategy, onCancel }: { traders:any[]; onSaved:()=>void; editStrategy?:any; onCancel?:()=>void }) {
 const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [traderId,setTraderId]=useState(""); const [starting,setStarting]=useState("200000"); const [minimum,setMinimum]=useState("5500"); const [maximum,setMaximum]=useState(""); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{if(editStrategy){setName(editStrategy.name||"");setDescription(editStrategy.description||"");setTraderId(editStrategy.trader_id||"");setStarting(String(editStrategy.starting_balance||""));setMinimum(String(editStrategy.minimum_investment||""));setMaximum(editStrategy.maximum_investment==null?"":String(editStrategy.maximum_investment));setMsg("")}},[editStrategy]);
 const selectedTrader=useMemo(()=>traders.find(t=>t.id===traderId),[traders,traderId]);
 const money=(v:string)=>{const n=Number(v);if(!Number.isFinite(n)||n<=0)return "—";return new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(n)};
 async function save(){
  setBusy(true);setMsg("");
  const cleanName=name.trim();
  const start=Number(starting), min=Number(minimum), max=maximum===""?null:Number(maximum);
  if(cleanName.length<2||cleanName.length>120){setMsg("Error: Strategy name must be between 2 and 120 characters.");setBusy(false);return}
  if(!traderId){setMsg("Error: Select an approved active trader.");setBusy(false);return}
  if(!Number.isFinite(start)||start<=0){setMsg("Error: Starting balance must be greater than zero.");setBusy(false);return}
  if(!Number.isFinite(min)||min<=0){setMsg("Error: Minimum investment must be greater than zero.");setBusy(false);return}
  if(max!==null&&(!Number.isFinite(max)||max<min)){setMsg("Error: Maximum investment cannot be below the minimum.");setBusy(false);return}
  const r=await fetch("/api/admin/strategies",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({strategyId:editStrategy?.id||null,name:cleanName,description:description.trim(),traderId,startingBalance:start,minimumInvestment:min,maximumInvestment:max,status:editStrategy?.status==="pending_review"?"active":(editStrategy?.status||"active")})});const d=await r.json();setMsg(r.ok?(editStrategy?"Strategy updated successfully.":"Strategy published successfully."):("Error: "+(d.error||"Unable to save.")));if(r.ok){if(!editStrategy){setName("");setDescription("");setTraderId("");setMaximum("")}onSaved()}setBusy(false)}
 const editing=!!editStrategy;
 return <section className="admin-card strategy-publisher">
  <div className="strategy-publisher-head"><div><div className="strategy-publisher-kicker"><span className="strategy-publisher-mark"><Sparkles size={12}/></span><span>{editing?"STRATEGY EDITOR":"STRATEGY OPERATIONS"}</span><i>ADMIN CONTROL</i></div><h2>{editing?"Edit strategy":"Publish a strategy"}</h2><p>{editing?"Update the strategy profile within the accounting safeguards. Historical performance cannot be rewritten.":"Define the investment shell, assign its trader, and make the strategy available for controlled investor access."}</p></div>{editing&&<button className="ghost" onClick={onCancel}><X size={14}/> Close editor</button>}</div>
  <div className="strategy-publisher-layout"><div className="strategy-publisher-form">
   <div className="strategy-form-section"><div className="strategy-section-title"><div className="strategy-section-icon"><FileText size={15}/></div><div><span>01 · STRATEGY IDENTITY</span><h3>Define the strategy</h3><p>Name and investor-facing mandate.</p></div></div>
    <div className="strategy-field-grid"><label className="strategy-field strategy-field-wide"><span>Strategy name <b>Required</b></span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. ZYNTH Alpha"/><small>2–120 characters.</small></label><label className="strategy-field strategy-field-wide"><span>Description</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the strategy's mandate, trading approach, and operating scope."/></label></div>
   </div>
   <div className="strategy-form-section"><div className="strategy-section-title"><div className="strategy-section-icon"><UserRound size={15}/></div><div><span>02 · STRATEGY OWNER</span><h3>Assign a trader</h3><p>Only approved active traders can own a strategy.</p></div></div>
    <label className="strategy-field"><span>Responsible trader <b>Required</b></span><select value={traderId} onChange={e=>setTraderId(e.target.value)}><option value="">Select an approved trader</option>{traders.map(t=><option key={t.id} value={t.id}>{t.full_name||t.email}</option>)}</select></label>
    {selectedTrader&&<div className="strategy-selected-trader"><div className="strategy-avatar"><UserRound size={15}/></div><div><strong>{selectedTrader.full_name||"Approved trader"}</strong><span>{selectedTrader.email||"Trader profile selected"}</span></div><CheckCircle2 size={16}/></div>}
   </div>
   <div className="strategy-form-section"><div className="strategy-section-title"><div className="strategy-section-icon"><CircleDollarSign size={15}/></div><div><span>03 · CAPITAL PARAMETERS</span><h3>Investment boundaries</h3><p>Limits may become locked after financial activity begins.</p></div></div>
    <div className="strategy-field-grid strategy-money-grid"><label className="strategy-field"><span>Starting balance <b>Required</b></span><div className="strategy-money-input"><em>₦</em><input type="number" min="0" value={starting} onChange={e=>setStarting(e.target.value)} disabled={editing&&!!(editStrategy?.total_units>0)}/></div></label><label className="strategy-field"><span>Minimum investment <b>Required</b></span><div className="strategy-money-input"><em>₦</em><input type="number" min="0" value={minimum} onChange={e=>setMinimum(e.target.value)} disabled={editing&&!!(editStrategy?.total_units>0)}/></div></label><label className="strategy-field"><span>Maximum investment</span><div className="strategy-money-input"><em>₦</em><input type="number" min="0" value={maximum} onChange={e=>setMaximum(e.target.value)} placeholder="No cap"/></div></label></div>
    <div className="strategy-capital-note"><ShieldCheck size={15}/><div><strong>Accounting protected</strong><span>Admin edits never rewrite NAV, settlements, investor units or historical reports.</span></div></div>
   </div>
   <div className="strategy-publish-bar"><div><span className="strategy-publish-label">FINAL CHECK</span><strong>{editing?"Save controlled changes?":"Ready to publish this strategy?"}</strong><small>{editing?"Changes are audited and accounting fields remain protected.":"Publishing creates the strategy shell and makes it available according to current investment settings."}</small></div><button className="strategy-publish-button" onClick={save} disabled={busy||!name.trim()||!traderId||Number(starting)<=0||Number(minimum)<=0||(maximum!==""&&Number(maximum)<Number(minimum))}>{busy?"Saving…":<>{editing?<CheckCircle2 size={15}/>:<Plus size={15}/>} {editing?"Save changes":"Publish strategy"}</>}</button></div>
   {msg&&<div className={"strategy-feedback "+(msg.startsWith("Error:")?"is-error":"is-success")}>{msg.startsWith("Error:")?"!":<CheckCircle2 size={15}/>}<span>{msg}</span></div>}
  </div>
  <aside className="strategy-publisher-preview"><div className="strategy-preview-card"><span className="strategy-preview-kicker">CONTROLLED PREVIEW</span><div className="strategy-preview-title"><div className="strategy-preview-symbol">{name.trim()?name.trim().slice(0,1).toUpperCase():"Z"}</div><div><strong>{name.trim()||"Your strategy"}</strong><span>{selectedTrader?.full_name||"Trader not assigned"}</span></div></div><div className="strategy-preview-metrics"><div><span>Starting balance</span><strong>{money(starting)}</strong></div><div><span>Minimum entry</span><strong>{money(minimum)}</strong></div><div><span>Maximum entry</span><strong>{maximum?money(maximum):"No cap"}</strong></div></div><div className="strategy-preview-description"><span>INVESTOR DESCRIPTION</span><p>{description.trim()||"Strategy description will appear here."}</p></div><div className="strategy-preview-status"><span className="strategy-live-dot"/><div><strong>Operational model</strong><small>Daily report · Admin confirmation · NAV settlement</small></div></div></div><div className="strategy-publisher-note"><ShieldCheck size={15}/><div><strong>Financial safety</strong><p>Used strategies cannot be hard-deleted. Archive is the safe terminal action.</p></div></div></aside></div>
 </section>
}