"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,CheckCircle2,Copy,Gift,Share2,Users,WalletCards,ShieldCheck,TrendingUp} from "lucide-react";
const money=(n:any)=>"₦"+Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});
const pct=(n:any)=>Number(n||0).toFixed(1)+"%";
const label=(s:string)=>String(s||"invited").replaceAll("_"," ");
export default function ReferralPage(){const[d,setD]=useState<any>({});const[e,setE]=useState("");const[m,setM]=useState("");
useEffect(()=>{fetch("/api/referral",{cache:"no-store"}).then(r=>r.json()).then(setD)},[]);
useEffect(()=>{const c=new URLSearchParams(location.search).get("ref");if(c)setE(c)},[]);
async function claim(){const r=await fetch("/api/referral",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:e})});const j=await r.json();setM(r.ok?"Referral attribution saved.":j.error||"Could not apply referral code.");if(r.ok)location.reload();}
async function copy(){await navigator.clipboard?.writeText(location.origin+(d.link||""));setM("Referral link copied.");}
const steps=["invited","verified","funded","invested","retained","reward_earned","reward_pending","reward_paid"];
return <main className="referral-page"><div className="referral-shell"><Link href="/dashboard" className="back-link"><ArrowLeft size={15}/> Dashboard</Link>
<header className="referral-user-hero"><div><span className="eyebrow">ZYNTH / GROWTH</span><h1>Refer. Build. Earn.</h1><p>Invite people you trust to ZYNTH. Your referral metrics are measured from authoritative account, funding, investment and reward records.</p></div><Gift size={42}/></header>
{!d.enabled&&<div className="referral-disabled">The referral programme is currently paused. Existing attribution and reward history remain preserved.</div>}
<section className="referral-link-card"><div><span className="muted">YOUR REFERRAL LINK</span><strong>{location.origin}{d.link||"/login?mode=signup"}</strong><small>Code: {d.code||"Generating…"}</small></div><div className="referral-link-actions"><button onClick={copy}><Copy size={15}/> Copy</button><button onClick={()=>{if(navigator.share)navigator.share({title:"Join ZYNTH",url:location.origin+d.link})}}><Share2 size={15}/> Share</button></div></section>
<div className="referral-stats">
<div><Users size={17}/><span>Total referrals</span><b>{d.total_referrals||0}</b></div><div><CheckCircle2 size={17}/><span>Verified</span><b>{d.verified||0}</b></div><div><WalletCards size={17}/><span>Funded</span><b>{d.funded||0}</b></div><div><TrendingUp size={17}/><span>Invested</span><b>{d.invested||0}</b></div><div><ShieldCheck size={17}/><span>Retained</span><b>{d.retained||0}</b></div><div><Gift size={17}/><span>Paid reward</span><b>{money(d.paid_rewards)}</b></div><div><Gift size={17}/><span>Pending reward</span><b>{money(d.pending_rewards)}</b></div><div><Gift size={17}/><span>Total reward</span><b>{money(d.total_reward)}</b></div></div>
<section className="referral-explainer"><div><span>01</span><h3>Invited → Verified</h3><p>Attribution is server-authoritative and survives email verification on another device.</p></div><div><span>02</span><h3>Funded → Invested</h3><p>Funding and investment are counted from confirmed ZYNTH records, not browser state.</p></div><div><span>03</span><h3>Retained → Paid</h3><p>Retention measures whether the referred investor stayed invested for the configured retention window; rewards remain pending until approved and credited.</p></div></section>
<section className="referral-admin-grid"><section className="admin-card"><div className="admin-card-head"><div><span className="muted">CONVERSION QUALITY</span><h2>Referral economics</h2></div></div><div className="referral-kpis"><div><span>Verified / Invited</span><b>{pct(d.conversion_rate)}</b></div><div><span>Funded / Invited</span><b>{pct(d.funded_conversion)}</b></div><div><span>Invested / Funded</span><b>{pct(d.investment_conversion)}</b></div><div><span>Retained / Invested</span><b>{pct(d.retention_rate)}</b></div><div><span>Revenue generated</span><b>{money(d.revenue_generated)}</b></div></div></section></section>
{d.referrals?.length>0&&<section className="referral-history panel"><div className="panel-head"><div><span className="muted">REFERRAL HISTORY</span><h2>Your network</h2></div></div>{d.referrals.map((r:any)=><div className="referral-history-row" key={r.id}><span className="avatar">R</span><div><b>{r.name}</b><small>{new Date(r.created_at).toLocaleDateString("en-NG")} · {label(r.lifecycle_state)}</small></div><strong>{label(r.lifecycle_state)}</strong></div>)}</section>}
<section className="referral-rules"><span className="muted">PROGRAMME RULES</span><p>Current qualifying minimum: <b>{money(d.min_qualifying_investment)}</b>. {d.percent_reward>0?("Reward rate: "+d.percent_reward+"%, capped at "+money(d.reward_cap)+"."):("Fixed reward: "+money(d.fixed_reward)+".")} Retention window: <b>{d.retention_days||10} days</b>.</p></section>
{m&&<div className="referral-toast">{m}</div>}
{e&&<section className="referral-claim panel"><span className="muted">REFERRAL CODE DETECTED</span><h2>{e}</h2><p>Apply this code to your account before you make a qualifying investment.</p><button className="primary" onClick={claim}>Apply referral code</button></section>}
</div></main>}