"use client";
import {useEffect,useMemo,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase/client";
import {ArrowLeft,CheckCircle2,ChevronRight,Clock3,Headphones,MessageCircle,Plus,RefreshCw,Send,ShieldCheck,Ticket,UserRound,X} from "lucide-react";
const fmt=(d:string)=>new Date(d).toLocaleString("en-NG",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"});
const label=(s:string)=>s.replaceAll("_"," ");
const categories=[["general","General help"],["account","Account"],["deposit","Deposit"],["withdrawal","Withdrawal"],["investment","Investment"],["redemption","Redemption"],["referral","Referral"],["technical","Technical"],["security","Security"]];
export default function SupportCenter(){
 const [tickets,setTickets]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[messages,setMessages]=useState<any[]>([]),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[composer,setComposer]=useState(""),[newOpen,setNewOpen]=useState(false),[subject,setSubject]=useState(""),[category,setCategory]=useState("general"),[notice,setNotice]=useState(""),[mobileList,setMobileList]=useState(true);
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 async function load(id?:string,quiet=false){if(!quiet)setLoading(true);try{const r=await fetch("/api/support"+(id?"?ticket="+encodeURIComponent(id):""),{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load support.");setTickets(j.tickets||[]);if(id&&j.ticket){setSelected(j.ticket);setMessages(j.messages||[])}else if(!id&&!selected&&j.tickets?.[0]){setSelected(j.tickets[0]);await load(j.tickets[0].id,true)}}catch(e){setNotice(e instanceof Error?e.message:"Could not load support.")}finally{if(!quiet)setLoading(false)}}
 useEffect(()=>{load();const channel=supabase.channel("zynth-support-user").on("postgres_changes",{event:"*",schema:"public",table:"zynth_support_tickets"},()=>load(selected?.id,true)).on("postgres_changes",{event:"INSERT",schema:"public",table:"zynth_support_messages"},()=>selected&&load(selected.id,true)).subscribe();const timer=setInterval(()=>load(selected?.id,true),15000);return()=>{clearInterval(timer);supabase.removeChannel(channel)}},[selected?.id]);
 async function openTicket(t:any){setSelected(t);setMobileList(false);await load(t.id,true)}
 async function createTicket(e:any){e.preventDefault();setSending(true);setNotice("");const r=await fetch("/api/support",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create",subject,category,body:composer})});const j=await r.json();if(!r.ok){setNotice(j.error||"Could not open support ticket.");setSending(false);return}setSubject("");setComposer("");setNewOpen(false);setSelected(j.ticket);setMobileList(false);await load(j.ticket.id,true);setSending(false)}
 async function send(){const body=composer.trim();if(!body||!selected||sending)return;setSending(true);setComposer("");const r=await fetch("/api/support",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"message",ticketId:selected.id,body})});const j=await r.json();if(!r.ok){setComposer(body);setNotice(j.error||"Message failed.");}else await load(selected.id,true);setSending(false)}
 async function closeTicket(){if(!selected)return;const r=await fetch("/api/support",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({ticketId:selected.id,status:selected.status==="closed"?"open":"closed"})});const j=await r.json();if(!r.ok)setNotice(j.error||"Could not update ticket.");else await load(selected.id,true)}
 return <section className="support-page">
  <header className="support-page-head"><div><div className="eyebrow-row"><span className="eyebrow">ZYNTH / CUSTOMER SERVICE</span><span className="live-dot"><i/> SUPPORT DESK</span></div><h1>How can we help?</h1><p>Talk to the ZYNTH support team. Every conversation is securely tracked as a support ticket.</p></div><button className="primary support-new" onClick={()=>{setNewOpen(true);setMobileList(false)}}><Plus size={16}/> New conversation</button></header>
  {notice&&<div className="admin-notice">{notice}<button onClick={()=>setNotice("")}><X size={14}/></button></div>}
  <div className={"support-shell "+(mobileList?"list-mode":"chat-mode")}>
   <aside className="support-inbox"><div className="support-inbox-head"><div><span className="muted">YOUR SUPPORT</span><h2>Conversations</h2></div><button className="icon-button" onClick={()=>load(undefined)} aria-label="Refresh"><RefreshCw size={15}/></button></div>
    {loading&&!tickets.length?<div className="support-loading">Loading your conversations…</div>:tickets.length?tickets.map(t=><button key={t.id} className={"support-ticket-preview "+(selected?.id===t.id?"active":"")} onClick={()=>openTicket(t)}><span className={"support-status-dot "+t.status}/><span className="support-preview-copy"><b>{t.subject}</b><small>{t.ticket_number} · {fmt(t.last_message_at)}</small></span>{t.user_unread_count>0&&<em>{t.user_unread_count}</em>}<ChevronRight size={14}/></button>):<div className="support-empty"><Ticket size={22}/><b>No conversations yet</b><p>Start a conversation whenever you need help with your ZYNTH account.</p><button className="text-action" onClick={()=>{setNewOpen(true);setMobileList(false)}}>Contact support <ChevronRight size={13}/></button></div>}
   </aside>
   <section className="support-chat">
    {newOpen?<form className="support-new-card" onSubmit={createTicket}><button type="button" className="support-back" onClick={()=>{setNewOpen(false);setMobileList(true)}}><ArrowLeft size={15}/> Back</button><div className="support-new-icon"><Headphones size={22}/></div><span className="muted">NEW SUPPORT CONVERSATION</span><h2>Tell us what you need.</h2><p>A support specialist will see your request and respond in this conversation.</p><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="e.g. My withdrawal is still pending" maxLength={160}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label>Message<textarea value={composer} onChange={e=>setComposer(e.target.value)} placeholder="Describe the issue and include anything that may help us investigate." maxLength={5000}/></label><button className="primary" disabled={sending||subject.trim().length<3||composer.trim().length<1}>{sending?"Opening…":"Open conversation"} <Send size={15}/></button></form>
    :selected?<><header className="support-chat-head"><button className="support-back mobile-only" onClick={()=>setMobileList(true)}><ArrowLeft size={15}/> Conversations</button><div className="support-chat-title"><span className={"support-status-dot "+selected.status}/><div><b>{selected.subject}</b><small>{selected.ticket_number} · {label(selected.category)} · {label(selected.status)}</small></div></div><button className="ghost" onClick={closeTicket}>{selected.status==="closed"?"Reopen":"Close ticket"}</button></header><div className="support-messages">{messages.map(m=><div key={m.id} className={"support-message "+(m.sender_role==="user"?"mine":"theirs")}><div className="support-bubble"><p>{m.body}</p><small>{m.sender_role==="admin"?"ZYNTH Support":"You"} · {fmt(m.created_at)}</small></div></div>)}<div className="support-response-note"><ShieldCheck size={14}/> Never share your password, PIN, OTP or full payment credentials in chat.</div></div><div className="support-composer"><textarea value={composer} onChange={e=>setComposer(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Write a message… Shift + Enter for a new line" maxLength={5000}/><button className="primary" onClick={send} disabled={sending||!composer.trim()} aria-label="Send message"><Send size={16}/></button></div></>:<div className="support-no-chat"><div className="support-new-icon"><MessageCircle size={24}/></div><h2>Your support desk</h2><p>Select a conversation or start a new one. Your complete conversation history stays here.</p><button className="primary" onClick={()=>{setNewOpen(true);setMobileList(false)}}><Plus size={15}/> Start a conversation</button></div>}
   </section>
  </div>
 </section>
}