"use client";
import {useEffect,useState} from "react";
import {AlertTriangle,CheckCircle2,Clock3,FileText,ShieldCheck,TriangleAlert} from "lucide-react";
export function RenderRules({text}:{text:string}){return <div className="rules-document">{text.split(/\n{2,}/).map((block,i)=>{const b=block.trim();if(!b)return null;if(b.startsWith("# ")){return <h1 key={i}>{b.slice(2)}</h1>}if(b.startsWith("## ")){return <h2 key={i}>{b.slice(3)}</h2>}if(b.startsWith("### ")){return <h3 key={i}>{b.slice(4)}</h3>}if(b.startsWith("- ")){return <ul key={i}>{b.split("\n").filter(Boolean).map((x,j)=><li key={j}>{x.slice(2)}</li>)}</ul>}if(/^\*\*.*\*\*$/.test(b)){return <div className="rules-callout" key={i}>{b.replaceAll("**","")}</div>}return <p key={i}>{b.split("\n").map((x,j)=><span key={j}>{x}{j<b.split("\n").length-1&&<br/>}</span>)}</p>})}</div>}
export default function TraderRulesView(){const[state,setState]=useState<any>({loading:true,rule:null,acknowledged:false,actions:[]});const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
async function load(){const r=await fetch("/api/trader/rules",{cache:"no-store"});const j=await r.json();setState({...j,loading:false})}useEffect(()=>{load()},[]);
async function acknowledge(){setBusy(true);const r=await fetch("/api/trader/rules/ack",{method:"POST"});const j=await r.json();setNotice(r.ok?"Rules acknowledged.":j.error||"Unable to acknowledge rules.");if(r.ok)await load();setBusy(false)}
if(state.loading)return <div className="trader-rules-loading"><Clock3 size={17}/> Loading Rules & Standards…</div>;
if(!state.rule)return <div className="trader-empty"><FileText size={22}/><h3>No published rules</h3><p>Operations has not published a Trader Rules & Standards document yet.</p></div>;
const warnings=(state.actions||[]).filter((x:any)=>x.action_type==="warning"&&x.status==="active").length;
return <div className="trader-pro-page trader-rules-page">
 <div className="trader-section-intro"><div><span>TRADER GOVERNANCE</span><h2>Rules & Standards</h2><p>The current operating standard for every ZYNTH trader entrusted with capital.</p></div><div className="rules-version"><FileText size={15}/><span>Version {state.rule.version}<small>{new Date(state.rule.published_at).toLocaleDateString("en-NG",{day:"2-digit",month:"short",year:"numeric"})}</small></span></div></div>
 {notice&&<div className="trader-global-notice"><CheckCircle2 size={15}/>{notice}</div>}
 <div className="rules-status-grid"><div><ShieldCheck size={17}/><span>Policy status<strong>Current</strong></span></div><div><AlertTriangle size={17}/><span>Active warnings<strong>{warnings} / 3</strong></span></div><div><CheckCircle2 size={17}/><span>Acknowledgement<strong>{state.acknowledged?"Completed":"Required"}</strong></span></div></div>
 {!state.acknowledged&&<section className="trader-rules-ack"><TriangleAlert size={19}/><div><strong>Review required</strong><p>You must read the current Rules & Standards and acknowledge this version.</p></div><button className="primary" onClick={acknowledge} disabled={busy}>{busy?"Saving…":"Acknowledge rules"}</button></section>}
 <section className="trader-pro-card rules-paper"><RenderRules text={state.rule.content}/></section>
 <section className="trader-pro-card rules-discipline"><div><span>DISCIPLINARY RECORD</span><h3>Your current record</h3></div>{(state.actions||[]).length?<div className="discipline-list">{state.actions.slice(0,8).map((a:any)=><div key={a.id}><span className={a.severity==="critical"?"critical":a.action_type==="warning"?"warning":"neutral"}>{a.action_type==="warning"?"Warning "+(a.warning_number||""):a.action_type}</span><b>{a.reason}</b><small>{new Date(a.created_at).toLocaleDateString("en-NG",{day:"2-digit",month:"short",year:"numeric"})}</small></div>)}</div>:<p className="rules-muted">No disciplinary actions recorded.</p>}</section>
 </div>}
