"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,CheckCircle2,Clock3,Eye,LoaderCircle,XCircle} from "lucide-react";
const money=(n:any)=>"₦"+Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});
const statusLabel:any={pending:"Pending",under_review:"Under review",processing:"Processing",paid:"Paid",rejected:"Rejected",cancelled:"Cancelled",failed:"Failed"};
export default function AdminWithdrawals(){
 const[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(""),[notice,setNotice]=useState(""),[selected,setSelected]=useState<any>(null),[reason,setReason]=useState("");
 const load=()=>fetch("/api/admin/withdrawals",{cache:"no-store"}).then(r=>r.json()).then(d=>{setRows(d.withdrawals||[]);if(d.error)setNotice(d.error)}).catch(()=>setNotice("Unable to load withdrawal queue."));
 useEffect(()=>{load()},[]);
 async function act(id:string,action:string){if(action==="reject"&&!reason.trim()){setNotice("Enter a rejection reason.");return}setBusy(id+action);setNotice("");const r=await fetch("/api/admin/withdrawals/action",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({withdrawalId:id,action,reason:reason.trim()||null})});const d=await r.json();if(!r.ok)setNotice(d.error||"Action failed.");else{setNotice("Withdrawal "+(statusLabel[d.status]||d.status)+".");setSelected(null);setReason("");await load()}setBusy("")}
 return <main className="dashboard-content"><header className="dashboard-header"><div><span className="eyebrow">ZYNTH / ADMIN / MONEY MOVEMENT</span><h1>Withdrawal operations.</h1><p>Reserved funds remain unavailable until the request is paid, rejected, or cancelled.</p></div><Link href="/admin" className="fund-btn secondary-dark"><ArrowLeft size={16}/> Admin</Link></header>
 <section className="panel"><div className="panel-head"><div><span className="muted">LIVE QUEUE</span><h2>Open withdrawals</h2></div><span className="admin-count">{rows.length} active</span></div>{notice&&<div className="form-feedback success">{notice}</div>}
 <div className="admin-table">{rows.map(w=><div className="admin-row" key={w.id}><div className="admin-person"><span className="avatar">{String(w.full_name||w.email||"U").slice(0,1).toUpperCase()}</span><span><b>{w.full_name||"Investor"}</b><small>{w.email} · {w.reference}</small></span></div><span>{money(w.gross_amount)} <small>{w.withdrawal_source||"wallet"}</small></span><span>{w.bank_name} · ••••{String(w.account_number||"").slice(-4)}</span><strong>{statusLabel[w.status]||w.status}</strong><button className="text-action" onClick={()=>setSelected(w)}><Eye size={14}/> Review</button></div>)}{!rows.length&&<div className="admin-empty"><Clock3 size={22}/><p>No active withdrawal requests.</p></div>}</div></section>
 {selected&&<div className="settlement-modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="settlement-modal" onMouseDown={e=>e.stopPropagation()}><header className="settlement-modal-head"><div><span className="muted">WITHDRAWAL REVIEW</span><h2>{selected.reference}</h2><p>{selected.full_name||selected.email} · {selected.withdrawal_source||"wallet"}</p></div><button className="icon-button" onClick={()=>setSelected(null)}><XCircle size={17}/></button></header><div className="settlement-summary-grid"><div><span>Gross</span><b>{money(selected.gross_amount)}</b></div><div><span>Fee</span><b>{money(selected.fee_amount)}</b></div><div><span>Net payout</span><b>{money(selected.net_amount)}</b></div><div><span>Age</span><b>{Number(selected.age_hours||0).toFixed(1)}h</b></div></div><div className="settlement-meta"><div><span>Bank</span><b>{selected.bank_name}</b></div><div><span>Account</span><b>{selected.account_name} · ••••{String(selected.account_number||"").slice(-4)}</b></div><div><span>Status</span><b>{statusLabel[selected.status]||selected.status}</b></div><div><span>Created</span><b>{new Date(selected.created_at).toLocaleString("en-NG")}</b></div></div>{selected.status!=="paid"&&selected.status!=="rejected"&&selected.status!=="cancelled"&&<><label className="input-label">REJECTION REASON</label><textarea className="settlement-note" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason recorded in the audit trail…"/><footer className="settlement-modal-actions"><button className="ghost" onClick={()=>setSelected(null)}>Close</button>{selected.status==="pending"&&<button className="ghost" disabled={!!busy} onClick={()=>act(selected.id,"review")}><Eye size={14}/> Review</button>}{(selected.status==="pending"||selected.status==="under_review")&&<button className="reject" disabled={!!busy} onClick={()=>act(selected.id,"reject")}><XCircle size={14}/> Reject</button>}{(selected.status==="pending"||selected.status==="under_review")&&<button className="approve" disabled={!!busy} onClick={()=>act(selected.id,"processing")}><LoaderCircle size={14}/> Mark processing</button>}{selected.status==="processing"&&<button className="approve" disabled={!!busy} onClick={()=>act(selected.id,"paid")}><CheckCircle2 size={14}/> Mark paid</button>}</footer></>}</section></div>}
 </main>
}
