"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, CheckCircle2, ChevronDown, Plus, ShieldCheck, WalletCards } from "lucide-react";

const naira=(n:number)=>`₦${Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export default function WithdrawPage(){
 const [balance,setBalance]=useState(0),[feePct,setFeePct]=useState(10),[minWithdrawal,setMinWithdrawal]=useState(1000),[enabled,setEnabled]=useState(true),[notice,setNotice]=useState("Withdrawals are reviewed manually. Most requests are processed during normal operations.");
 const [accounts,setAccounts]=useState<any[]>([]),[selected,setSelected]=useState(""),[showAdd,setShowAdd]=useState(false);
 const [bank,setBank]=useState(""),[accountNumber,setAccountNumber]=useState(""),[accountName,setAccountName]=useState("");
 const [amount,setAmount]=useState(""),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[ok,setOk]=useState(false);
 const load=()=>{fetch("/api/account/summary").then(r=>r.ok?r.json():null).then(d=>{if(d){setBalance(Number(d.available||0));setFeePct(Number(d.exitFeePct??10));setMinWithdrawal(Number(d.minWithdrawal??1000));setEnabled(d.withdrawalsEnabled!==false);}}).catch(()=>{});fetch("/api/withdrawals/beneficiaries").then(r=>r.ok?r.json():null).then(d=>{const a=d?.beneficiaries||[];setAccounts(a);setSelected(a.find((x:any)=>x.is_default)?.id||a[0]?.id||"");}).catch(()=>{});};
 useEffect(()=>{load()},[]);
 const gross=Number(amount)||0,fee=gross*feePct/100,net=Math.max(0,gross-fee);
 async function addAccount(){setSaving(true);setMsg("");try{const r=await fetch("/api/withdrawals/beneficiaries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({bankName:bank,accountNumber,accountName})});const d=await r.json();if(!r.ok){setMsg(d.error||"Unable to save account.");return}setAccounts(a=>[d.beneficiary,...a]);setSelected(d.beneficiary.id);setBank("");setAccountNumber("");setAccountName("");setShowAdd(false)}finally{setSaving(false)}}
 async function submit(){if(!selected){setMsg("Select a payout account first.");return}setBusy(true);setMsg("");setOk(false);try{const r=await fetch("/api/transactions/withdraw",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount:gross,beneficiaryId:selected})});const d=await r.json();if(!r.ok){setMsg(d.error||"Unable to submit withdrawal.");return}setOk(true);setMsg("Withdrawal submitted. Your funds are reserved while the request is reviewed.");setAmount("");if(d.withdrawal?.withdrawal_id)window.location.href=`/dashboard/withdrawal/${d.withdrawal.withdrawal_id}`;else load()}catch{setMsg("Unable to connect. Please try again.");}finally{setBusy(false)}}
 const selectedAccount=accounts.find(a=>a.id===selected);
 return <section className="dashboard-content"><header className="dashboard-header"><div><span className="eyebrow">ZYNTH / WITHDRAW</span><h1>Withdraw available funds.</h1><p>Review your payout destination and the exact amount you will receive.</p></div><Link className="fund-btn secondary-dark" href="/dashboard"><ArrowLeft size={16}/> Overview</Link></header>
 <div className="withdraw-grid"><section className="panel withdraw-card">
  {!enabled?<div className="withdraw-disabled"><ShieldCheck size={20}/><div><b>Withdrawals are temporarily unavailable</b><p>Please check back later. Your available balance remains safe.</p></div></div>:<>
  <div className="withdraw-balance"><WalletCards size={18}/><div><span>Available balance</span><b>{naira(balance)}</b></div><small>MIN {naira(minWithdrawal)}</small></div>
  <label className="input-label">GROSS WITHDRAWAL</label><div className="money-input"><span>₦</span><input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00" aria-label="Withdrawal amount"/></div>
  <div className="withdraw-breakdown"><div><span>Withdrawal amount</span><b>{naira(gross)}</b></div><div><span>Exit fee ({feePct}%)</span><b>−{naira(fee)}</b></div><div className="net"><span>You receive</span><b>{naira(net)}</b></div></div>
  <div className="beneficiary-picker"><div className="picker-head"><div><span className="muted">PAYOUT ACCOUNT</span><b>{selectedAccount?selectedAccount.bank_name:"No account saved"}</b></div><button onClick={()=>setShowAdd(v=>!v)}><Plus size={14}/> {showAdd?"Close":"Add account"}</button></div>{accounts.length?<><div className="select-wrap"><select value={selected} onChange={e=>setSelected(e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.bank_name} · {a.account_name} · ••••{a.account_number.slice(-4)}</option>)}</select><ChevronDown size={15}/></div><small className="verified-line"><ShieldCheck size={13}/> Destination is saved to this withdrawal request for audit tracking.</small></>:<p className="empty-account">Add the bank account that should receive your payout.</p>}</div>
  {showAdd&&<div className="beneficiary-form"><label>Bank name<input value={bank} onChange={e=>setBank(e.target.value)} placeholder="e.g. Access Bank"/></label><label>Account number<input inputMode="numeric" maxLength={10} value={accountNumber} onChange={e=>setAccountNumber(e.target.value.replace(/\D/g,""))} placeholder="10-digit account number"/></label><label>Account name<input value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="Account holder name"/></label><button className="secondary-btn" onClick={addAccount} disabled={saving}>{saving?"Saving…":"Save payout account"}</button></div>}
  <button className="primary full-button" onClick={submit} disabled={busy||gross<minWithdrawal||gross>balance||!selected}>{busy?"Submitting…":"Review & submit withdrawal"} <ArrowUpRight size={16}/></button>
  {gross>0&&gross<minWithdrawal&&<p className="withdraw-hint">Minimum withdrawal is {naira(minWithdrawal)}.</p>}
  {msg&&<div className={"form-feedback "+(ok?"success":"")}><CheckCircle2 size={15}/>{msg}</div>}
  </>}
 </section>
 <aside className="panel"><span className="muted">WITHDRAWAL POLICY</span><h2>Clear before you confirm</h2><div className="withdraw-note"><ShieldCheck size={18}/><p>{notice}</p></div><div className="withdraw-note"><WalletCards size={18}/><p>Funds are reserved immediately. You can cancel while the request is still submitted. Rejected requests return the full gross amount.</p></div><Link href="/dashboard/transactions" className="text-action">View withdrawal history <ArrowUpRight size={14}/></Link></aside></div></section>
}