import { createHmac } from "crypto";
import { decryptProviderSecret } from "@/lib/secure-provider-secrets";
export const NOWPAYMENTS_BASE="https://api.nowpayments.io/v1";
export async function getNowPaymentsSettings(adminClient:any){const {data,error}=await adminClient.from("zynth_payment_provider_settings").select("*").eq("provider","nowpayments").maybeSingle();if(error)throw error;if(!data)throw new Error("NOWPayments settings are not initialized.");return data;}
export function requireApiKey(settings:any){if(!settings.api_key_ciphertext)throw new Error("NOWPayments API key is not configured.");return decryptProviderSecret(settings.api_key_ciphertext);}
export function requireIpnSecret(settings:any){if(!settings.ipn_secret_ciphertext)throw new Error("NOWPayments IPN secret is not configured.");return decryptProviderSecret(settings.ipn_secret_ciphertext);}
export async function nowRequest(path:string,apiKey:string,init:RequestInit={}){const headers=new Headers(init.headers);headers.set("x-api-key",apiKey);headers.set("accept","application/json");if(init.body)headers.set("content-type","application/json");const r=await fetch(NOWPAYMENTS_BASE+path,{...init,headers,cache:"no-store"});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(body?.message||body?.error||`NOWPayments request failed (${r.status}).`));return body;}
export function sortObject(value:any):any{if(Array.isArray(value))return value.map(sortObject);if(value&&typeof value==="object")return Object.keys(value).sort().reduce((out,key)=>{out[key]=sortObject(value[key]);return out},{} as any);return value;}
export function verifyNowPaymentsSignature(payload:any,signature:string,secret:string){const expected=createHmac("sha512",secret).update(JSON.stringify(sortObject(payload))).digest("hex");return expected===String(signature||"").trim();}
export function normalizeNowStatus(status:string){const s=String(status||"").toLowerCase();if(["waiting","confirming","confirmed","finished","failed","expired","refunded","partially_paid","sending"].includes(s))return s;return s||"unknown";}