import {NextResponse} from "next/server";
import crypto from "crypto";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {createSupabaseAdminClient} from "@/lib/supabase/admin";
function esc(s:string){return s.replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/\r?\n/g," ")}
function pdfFromSnapshot(s:any){
 const money=(n:any)=>"NGN "+Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});
 const lines=["ZYNTH — VAULT STATEMENT","","Account ID: "+s.account_id,"Statement period: "+s.statement_period.start+" to "+s.statement_period.end,"","Opening balance: "+money(s.opening_balance),"Deposits: "+money(s.deposits),"Investments: "+money(s.investments),"Investment return: "+money(s.returns),"Fees: "+money(s.fees),"Withdrawals: "+money(s.withdrawals),"Redemptions: "+money(s.redemptions),"Closing value: "+money(s.closing_value),"Ending NAV: "+(Array.isArray(s.ending_nav)&&s.ending_nav.length===1?Number(s.ending_nav[0].nav||0).toFixed(4):"Multiple / see transaction summary"),"","Transaction summary:"];
 for(const t of (s.transaction_summary||[]).slice(-24)) lines.push(String(t.date).slice(0,10)+"  "+String(t.type)+"  "+money(t.amount)+"  "+String(t.reference||""));
 lines.push("","This statement is an immutable ZYNTH record. Corrections are issued as revised versions.");
 const body=lines.map((x,i)=>"BT /F1 9 Tf 50 "+(790-i*18)+" Td ("+esc(x)+") Tj ET").join("\n");
 const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>","<< /Length "+Buffer.byteLength(body)+" >>\nstream\n"+body+"\nendstream","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"];
 let out="%PDF-1.4\n",offsets=[0];for(let i=0;i<objects.length;i++){offsets[i+1]=Buffer.byteLength(out);out+=(i+1)+" 0 obj\n"+objects[i]+"\nendobj\n"}const xref=Buffer.byteLength(out);out+="xref\n0 6\n0000000000 65535 f \n";for(let i=1;i<=5;i++)out+=String(offsets[i]).padStart(10,"0")+" 00000 n \n";out+="trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n"+xref+"\n%%EOF";return Buffer.from(out,"utf8");
}
function datesFor(mode:string,from?:string,to?:string,earliest?:string){const now=new Date();let start="",end="";if(mode==="custom"){start=from||"";end=to||""}else if(mode==="since_inception"){start=earliest||now.toISOString().slice(0,10);end=now.toISOString().slice(0,10)}else{const y=now.getUTCFullYear(),m=now.getUTCMonth();start=new Date(Date.UTC(y,m-1,1)).toISOString().slice(0,10);end=new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)}return{start,end}}
export async function GET(req:Request){try{const s=await createSupabaseServerClient();const{data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({error:"Authentication required."},{status:401});const{data,error}=await s.rpc("zynth_statement_periods",{p_user_id:user.id});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({statements:data||[]},{headers:{"Cache-Control":"no-store"}})}catch(e:any){return NextResponse.json({error:e.message||"Unable to load statements."},{status:500})}}
export async function POST(req:Request){try{const s=await createSupabaseServerClient();const{data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({error:"Authentication required."},{status:401});const b=await req.json().catch(()=>({}));const admin=createSupabaseAdminClient();const{data:events}=await admin.from("zynth_investment_events").select("created_at").eq("user_id",user.id).order("created_at",{ascending:true}).limit(1);const earliest=events?.[0]?.created_at?.slice(0,10);const d=datesFor(String(b.periodType||"monthly"),b.from,b.to,earliest);if(!d.start||!d.end||d.end<d.start)return NextResponse.json({error:"Invalid statement period."},{status:400});const{data:snapshot,error:se}=await admin.rpc("zynth_vault_statement_snapshot",{p_user_id:user.id,p_period_start:d.start,p_period_end:d.end});if(se)return NextResponse.json({error:se.message},{status:400});const pdf=pdfFromSnapshot(snapshot);const hash=crypto.createHash("sha256").update(pdf).digest("hex");const{data:inserted,error:ie}=await admin.rpc("zynth_statement_insert",{p_user_id:user.id,p_period_type:String(b.periodType||"custom"),p_period_start:d.start,p_period_end:d.end,p_snapshot:snapshot,p_pdf_bytes:pdf,p_content_hash:hash});if(ie)return NextResponse.json({error:ie.message},{status:400});return NextResponse.json({statement:inserted,snapshot},{status:201})}catch(e:any){return NextResponse.json({error:e.message||"Unable to generate statement."},{status:500})}}
