"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowDownRight,ArrowUpRight,Clock3,LockKeyhole,Plus,ShieldCheck,TrendingUp,WalletCards} from "lucide-react";
const money=(n:any)=>"₦"+Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});
const dt=(v:any)=>v?new Date(v).toLocaleString("en-NG",{dateStyle:"medium",timeStyle:"short"}):"—";
export default function Investments(){
 const[strategies,setStrategies]=useState<any[]>([]),[positions,setPositions]=useState<any[]>([]),[redemptions,setRedemptions]=useState<any[]>([]),[cash,setCash]=useState(0),[amounts,setAmounts]=useState<Record<string,string>>({}),[topups,setTopups]=useState<Record<string,string>>({}),[exits,setExits]=useState<Record<string,string>>({}),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 async function load(){try{const[a,p,m]=await Promise.all([fetch("/api/account/summary").then(r=>r.json()),fetch("/api/strategies").then(r=>r.json()),fetch("/api/investments/mine").then(r=>r.json())]);setCash(Number(a.summary?.cash||0));setStrategies(p.strategies||[]);setPositions(m.investments||[]);setRedemptions(m.redemptions||[])}catch{}}
 useEffect(()=>{load()},[]);
 async function invest(id:string){const amount=Number(amounts[id]||0),s=strategies.find(x=>x.id===id);if(!Number.isFinite(amount)||amount<=0){setMsg("Enter a valid investment amount.");return}if(s?.minimum_investment&&amount<Number(s.minimum_investment)){setMsg("Minimum investment is "+money(s.minimum_investment)+".");return}if(s?.maximum_investment&&amount>Number(s.maximum_investment)){setMsg("Maximum investment is "+money(s.maximum_investment)+".");return}setBusy("invest:"+id);setMsg("");const r=await fetch("/api/investments/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({strategyId:id,amount})});const d=await r.json();if(r.ok){setMsg("Investment activated.");await load();setBusy("");return}if(d.code==="INSUFFICIENT_AVAILABLE_BALANCE"){const dep=await fetch("/api/deposits/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount,method:"manual",strategyId:id})});const dd=await dep.json();if(!dep.ok){setMsg(dd.error||"Unable to start funding.");setBusy("");return}window.location.href="/dashboard/deposit/"+dd.request.id+"?returnTo="+encodeURIComponent("/dashboard/investments");return}setMsg(d.error||"Unable to invest.");setBusy("")}
 async function topup(id:string){const amount=Number(topups[id]||0);if(!Number.isFinite(amount)||amount<=0){setMsg("Enter a valid top-up amount.");return}setBusy("topup:"+id);setMsg("");const r=await fetch("/api/investments/topup",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({investmentId:id,amount})});const d=await r.json();if(r.ok){setMsg("Top-up completed at the current NAV.");await load();setBusy("");return}if(d.code==="INSUFFICIENT_AVAILABLE_BALANCE"){const dep=await fetch("/api/investments/topup/deposit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({investmentId:id,amount})});const dd=await dep.json();if(!dep.ok){setMsg(dd.error||"Unable to start top-up funding.");setBusy("");return}window.location.href="/dashboard/deposit/"+dd.request.id+"?returnTo="+encodeURIComponent("/dashboard/investments");return}setMsg(d.error||"Unable to top up.");setBusy("")}
 async function exit(id:string){const amount=Number(exits[id]||0);if(!Number.isFinite(amount)||amount<=0){setMsg("Enter the amount you want to redeem.");return}setBusy("exit:"+id);setMsg("");const r=await fetch("/api/investments/redemptions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({investmentId:id,amount})});const d=await r.json();if(r.ok){setMsg("Redemption submitted. Your units are reserved at the confirmed NAV.");await load();setBusy("");return}setMsg(d.error||"Unable to request redemption.");setBusy("")}
 async function cancel(id:string){setBusy("cancel:"+id);const r=await fetch("/api/investments/redemptions/cancel",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({redemptionId:id})});const d=await r.json();setMsg(r.ok?"Redemption cancelled and the position restored.":(d.error||"Unable to cancel redemption."));await load();setBusy("")}
 return <section className="dashboard-content"><header className="dashboard-header premium-header"><div><div className="eyebrow-row"><span className="eyebrow">ZYNTH / INVESTMENTS</span><span className="live-dot"><i/> NAV ACCOUNTING</span></div><h1>Investments, with control.</h1><p>Top up existing positions, request exits, and see exactly when proceeds become available.</p></div><Link className="fund-btn secondary-dark" href="/dashboard"><ArrowUpRight size={15}/> Overview</Link></header>
 <div className="wealth-hero"><div className="wealth-main"><div className="wealth-label"><span>Available cash</span><span className="secure-chip"><ShieldCheck size={13}/> Ready</span></div><strong>{money(cash)}</strong><div className="wealth-breakdown"><span><i className="dot available"/> Available</span><span><i className="dot locked"/> Active positions {positions.length}</span></div></div><div className="wealth-side"><div><span>Active positions</span><b>{positions.filter(x=>x.status==="active").length}</b></div><div><span>Pending exits</span><b>{redemptions.filter(x=>["pending","approved","processing"].includes(x.status)).length}</b></div><div><span>Model</span><b>NAV + units</b></div></div></div>
 {msg&&<div className="notice">{msg}</div>}
 <section className="panel"><div className="panel-head"><div><span className="muted">YOUR PORTFOLIO</span><h2>Active strategy positions</h2></div></div><div className="dashboard-grid">{positions.filter(x=>x.status==="active").map(i=><article className="panel" key={i.id}><div className="panel-head"><div><span className="status-badge"><i/> ACTIVE</span><h2>{i.zynth_strategies?.name||"Strategy"}</h2></div><span className="secure-chip"><LockKeyhole size={12}/> Unit position</span></div><div className="vault-card-amount">{money(i.current_value)}</div><div className="health-grid"><div><span>Principal</span><b>{money(i.principal_remaining)}</b></div><div><span>Units</span><b>{Number(i.units).toFixed(6)}</b></div><div><span>Entry NAV</span><b>{Number(i.entry_nav).toFixed(4)}</b></div><div><span>Current NAV</span><b>{Number(i.zynth_strategies?.nav||0).toFixed(4)}</b></div></div><div className="money-input" style={{marginTop:18}}><span>₦</span><input inputMode="decimal" placeholder="Top-up amount" value={topups[i.id]||""} onChange={e=>setTopups({...topups,[i.id]:e.target.value})}/><button className="primary" disabled={busy==="topup:"+i.id} onClick={()=>topup(i.id)}><Plus size={15}/> Top up</button></div><div className="money-input" style={{marginTop:10}}><span>₦</span><input inputMode="decimal" placeholder="Redemption amount" value={exits[i.id]||""} onChange={e=>setExits({...exits,[i.id]:e.target.value})}/><button className="ghost" disabled={busy==="exit:"+i.id} onClick={()=>exit(i.id)}><ArrowDownRight size={15}/> Request exit</button></div><small>Exits use the latest confirmed NAV. Fees, approval and release timing are controlled by operations.</small></article>)}</div>{!positions.filter(x=>x.status==="active").length&&<div className="premium-empty"><TrendingUp size={21}/><h3>No active investments yet</h3><p>Choose a live strategy below to start building your portfolio.</p></div>}</section>
 <section className="panel"><div className="panel-head"><div><span className="muted">REDEMPTION ACTIVITY</span><h2>Exit timeline</h2></div></div><div className="activity-list">{redemptions.map(r=><div className="activity-row" key={r.id}><span className="activity-icon neutral">{r.status==="released"?<WalletCards size={16}/>:<Clock3 size={16}/>}</span><span className="activity-info"><b>{r.zynth_strategies?.name||"Strategy"} · {money(r.net_amount)} net</b><small>{r.status.toUpperCase()} · Requested {dt(r.requested_at)} · Release {dt(r.release_at)}</small></span><span>{r.status==="pending"&&<button className="text-action" disabled={busy==="cancel:"+r.id} onClick={()=>cancel(r.id)}>Cancel</button>}</span></div>)}{!redemptions.length&&<div className="activity-empty"><Clock3 size={18}/><span>No redemption requests yet.</span></div>}</div></section>
 <section className="panel"><div className="panel-head"><div><span className="muted">STRATEGY MARKET</span><h2>Explore live strategies</h2></div><span className="secure-chip"><ShieldCheck size={12}/> Confirmed settlement</span></div><div className="dashboard-grid">{strategies.map(s=><section className="panel" key={s.id}><div className="panel-head"><div><span className="muted">ACTIVE STRATEGY</span><h2>{s.name}</h2></div><span className="status-badge"><i/> LIVE</span></div><p className="copy">{s.description||"A ZYNTH-managed strategy with daily performance confirmed by operations."}</p><div className="health-grid"><div><span>Current NAV</span><b>₦{Number(s.nav).toFixed(4)}</b></div><div><span>Minimum</span><b>{money(s.minimum_investment)}</b></div><div><span>Trader</span><b>{s.trader_name||"Assigned"}</b></div><div><span>Maximum</span><b>{s.maximum_investment?money(s.maximum_investment):"No cap"}</b></div></div><div className="money-input" style={{marginTop:18}}><span>₦</span><input inputMode="decimal" placeholder="Investment amount" value={amounts[s.id]||""} onChange={e=>setAmounts({...amounts,[s.id]:e.target.value})}/><button className="primary full-button" disabled={busy==="invest:"+s.id} onClick={()=>invest(s.id)}><TrendingUp size={16}/> Invest in {s.name}</button></div></section>)}</div>{!strategies.length&&<div className="premium-empty"><TrendingUp size={21}/><h3>No strategies are open yet</h3><p>The operations team will publish strategies here when ready.</p></div>}</section>
 </section>
}
