-- Phase 5 risk engine repository parity
create table if not exists public.zynth_risk_events(
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade,
 event_type text not null, source text not null, occurred_at timestamptz not null default now(),
 risk_points integer not null default 0, entity_type text, entity_id text, ip_hash text, device_id uuid, country_code text, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.zynth_risk_rules(rule_key text primary key,name text not null,description text,enabled boolean not null default true,points integer not null default 0,threshold_count integer not null default 1,window_minutes integer not null default 1440,action text not null default 'FLAG',config jsonb not null default '{}',updated_at timestamptz not null default now());
create table if not exists public.zynth_risk_scores(user_id uuid primary key references public.users(id) on delete cascade,score integer not null default 0,classification text not null default 'LOW',calculated_at timestamptz not null default now(),contributing_events jsonb not null default '[]',last_high_risk_at timestamptz,updated_at timestamptz not null default now());
create table if not exists public.zynth_risk_cases(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,score integer not null default 0,classification text not null,status text not null default 'OPEN',action text not null default 'NONE',reason text,opened_at timestamptz not null default now(),reviewed_at timestamptz,reviewer_user_id uuid references public.users(id),resolution_note text,metadata jsonb not null default '{}',updated_at timestamptz not null default now());
alter table public.zynth_risk_events enable row level security; alter table public.zynth_risk_rules enable row level security; alter table public.zynth_risk_scores enable row level security; alter table public.zynth_risk_cases enable row level security;
revoke all on public.zynth_risk_events,public.zynth_risk_rules,public.zynth_risk_scores,public.zynth_risk_cases from anon,authenticated,public; grant all on public.zynth_risk_events,public.zynth_risk_rules,public.zynth_risk_scores,public.zynth_risk_cases to service_role;
