-- Phase 4 KYC / AML server-authoritative RPCs
create or replace function public.zynth_kyc_ensure_profile() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare p public.zynth_kyc_profiles%rowtype; begin if auth.uid() is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
insert into public.zynth_kyc_profiles(user_id) values(auth.uid()) on conflict do nothing; select * into p from public.zynth_kyc_profiles where user_id=auth.uid();
return jsonb_build_object('user_id',p.user_id,'status',p.status,'verification_level',p.verification_level,'risk_classification',p.risk_classification,'verified_at',p.verified_at,'expires_at',p.expires_at,'next_review_due_at',p.next_review_due_at); end $$;
create or replace function public.zynth_kyc_profile() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare p public.zynth_kyc_profiles%rowtype; a jsonb; begin if auth.uid() is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
insert into public.zynth_kyc_profiles(user_id) values(auth.uid()) on conflict do nothing; select * into p from public.zynth_kyc_profiles where user_id=auth.uid();
select coalesce(jsonb_agg(jsonb_build_object('id',id,'address_type',address_type,'line1',line1,'line2',line2,'city',city,'state_region',state_region,'postal_code',postal_code,'country',country,'verification_method',verification_method,'status',status,'verification_date',verification_date) order by created_at desc),'[]'::jsonb) into a from public.zynth_kyc_addresses where user_id=auth.uid();
return jsonb_build_object('profile',jsonb_build_object('status',p.status,'verification_level',p.verification_level,'legal_first_name',p.legal_first_name,'legal_middle_name',p.legal_middle_name,'legal_last_name',p.legal_last_name,'date_of_birth',p.date_of_birth,'nationality',p.nationality,'country_of_residence',p.country_of_residence,'tax_residency',p.tax_residency,'source_of_funds',p.source_of_funds,'source_of_funds_status',p.source_of_funds_status,'source_of_wealth',p.source_of_wealth,'source_of_wealth_status',p.source_of_wealth_status,'risk_classification',p.risk_classification,'verified_at',p.verified_at,'expires_at',p.expires_at,'next_review_due_at',p.next_review_due_at),'addresses',a); end $$;
create or replace function public.zynth_kyc_submit_profile(p_first_name text,p_middle_name text,p_last_name text,p_dob date,p_nationality text,p_country_of_residence text,p_tax_residency text,p_source_of_funds text,p_source_of_wealth text,p_address jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare oldp public.zynth_kyc_profiles%rowtype; newp public.zynth_kyc_profiles%rowtype; aid uuid; begin if auth.uid() is null then raise exception 'AUTHENTICATION_REQUIRED'; end if;
insert into public.zynth_kyc_profiles(user_id) values(auth.uid()) on conflict do nothing; select * into oldp from public.zynth_kyc_profiles where user_id=auth.uid() for update; if oldp.status='SUSPENDED' then raise exception 'KYC_SUSPENDED'; end if;
update public.zynth_kyc_profiles set legal_first_name=nullif(trim(p_first_name),''),legal_middle_name=nullif(trim(p_middle_name),''),legal_last_name=nullif(trim(p_last_name),''),date_of_birth=p_dob,nationality=nullif(trim(p_nationality),''),country_of_residence=nullif(trim(p_country_of_residence),''),tax_residency=nullif(trim(p_tax_residency),''),source_of_funds=nullif(trim(p_source_of_funds),''),source_of_funds_status=case when nullif(trim(p_source_of_funds),'') is null then source_of_funds_status else 'PENDING' end,source_of_wealth=nullif(trim(p_source_of_wealth),''),source_of_wealth_status=case when nullif(trim(p_source_of_wealth),'') is null then source_of_wealth_status else 'PENDING' end,status=case when status in ('NOT_STARTED','REJECTED','REVERIFICATION_REQUIRED') then 'PENDING' else status end,updated_at=now() where user_id=auth.uid() returning * into newp;
if p_address is not null and jsonb_typeof(p_address)='object' and nullif(trim(p_address->>'line1'),'') is not null and nullif(trim(p_address->>'country'),'') is not null then insert into public.zynth_kyc_addresses(user_id,address_type,line1,line2,city,state_region,postal_code,country,status) values(auth.uid(),coalesce(nullif(upper(p_address->>'address_type'),''),'RESIDENTIAL'),trim(p_address->>'line1'),nullif(trim(p_address->>'line2'),''),nullif(trim(p_address->>'city'),''),nullif(trim(p_address->>'state_region'),''),nullif(trim(p_address->>'postal_code'),''),trim(p_address->>'country'),'PENDING') returning id into aid; end if;
insert into public.zynth_kyc_review_history(user_id,action,from_status,to_status,notes,metadata) values(auth.uid(),'SUBMITTED',oldp.status,newp.status,'KYC profile submitted',jsonb_build_object('address_id',aid)); return jsonb_build_object('ok',true,'status',newp.status); end $$;
create or replace function public.zynth_kyc_submit_document(p_document_type text,p_issuing_country text,p_document_reference text,p_evidence_reference text,p_expiration_date date) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare did uuid; begin if auth.uid() is null then raise exception 'AUTHENTICATION_REQUIRED'; end if; if p_document_type not in ('PASSPORT','NATIONAL_ID','DRIVERS_LICENSE','RESIDENCE_PERMIT','UTILITY_BILL','BANK_STATEMENT','TAX_DOCUMENT','SELFIE','OTHER') then raise exception 'INVALID_DOCUMENT_TYPE'; end if; if nullif(trim(p_document_reference),'') is null then raise exception 'DOCUMENT_REFERENCE_REQUIRED'; end if;
insert into public.zynth_kyc_documents(user_id,document_type,issuing_country,document_reference,evidence_reference,expiration_date) values(auth.uid(),p_document_type,nullif(trim(p_issuing_country),''),trim(p_document_reference),nullif(trim(p_evidence_reference),''),p_expiration_date) returning id into did;
update public.zynth_kyc_profiles set status=case when status='NOT_STARTED' then 'PENDING' else status end,updated_at=now() where user_id=auth.uid(); insert into public.zynth_kyc_review_history(user_id,action,notes,metadata) values(auth.uid(),'SUBMITTED','KYC document submitted',jsonb_build_object('document_id',did,'document_type',p_document_type)); return jsonb_build_object('ok',true,'document_id',did); end $$;
create or replace function public.zynth_kyc_admin_list(p_admin_id uuid,p_search text default null,p_status text default null,p_risk text default null,p_limit int default 50,p_offset int default 0) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare out jsonb; begin if auth.uid() is null or auth.uid()<>p_admin_id or not public.zynth_has_role(auth.uid(),'admin') then raise exception 'ADMIN_AUTHORIZATION_REQUIRED'; end if;
select jsonb_build_object('total',count(*),'items',coalesce(jsonb_agg(to_jsonb(x) order by x.updated_at desc),'[]'::jsonb)) into out from (select p.user_id,u.email,u.full_name,u.account_status,p.status,p.verification_level,p.risk_classification,p.verified_at,p.expires_at,p.next_review_due_at,p.updated_at from public.zynth_kyc_profiles p join public.users u on u.id=p.user_id where (p_search is null or p_search='' or u.email ilike '%'||p_search||'%' or u.full_name ilike '%'||p_search||'%' or p.user_id::text ilike '%'||p_search||'%') and (p_status is null or p.status=p_status) and (p_risk is null or p.risk_classification=p_risk) order by p.updated_at desc limit greatest(1,least(coalesce(p_limit,50),100)) offset greatest(coalesce(p_offset,0),0)) x; return out; end $$;
create or replace function public.zynth_kyc_admin_detail(p_admin_id uuid,p_user_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare p jsonb; docs jsonb; adds jsonb; screens jsonb; history jsonb; u record; begin if auth.uid() is null or auth.uid()<>p_admin_id or not public.zynth_has_role(auth.uid(),'admin') then raise exception 'ADMIN_AUTHORIZATION_REQUIRED'; end if; select * into u from public.users where id=p_user_id; if not found then raise exception 'USER_NOT_FOUND'; end if; insert into public.zynth_kyc_profiles(user_id) values(p_user_id) on conflict do nothing; select to_jsonb(x) into p from (select * from public.zynth_kyc_profiles where user_id=p_user_id) x; select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb) into docs from (select id,document_type,issuing_country,document_reference,verification_provider,verification_status,submitted_at,verified_at,expiration_date,reviewer_user_id,rejection_reason,evidence_reference,metadata,created_at,updated_at from public.zynth_kyc_documents where user_id=p_user_id) x; select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb) into adds from (select * from public.zynth_kyc_addresses where user_id=p_user_id) x; select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb) into screens from (select * from public.zynth_kyc_screenings where user_id=p_user_id) x; select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb) into history from (select * from public.zynth_kyc_review_history where user_id=p_user_id limit 100) x; return jsonb_build_object('profile',p,'documents',docs,'addresses',adds,'screenings',screens,'history',history,'user',jsonb_build_object('id',u.id,'email',u.email,'full_name',u.full_name,'account_status',u.account_status)); end $$;
create or replace function public.zynth_kyc_admin_update(p_admin_id uuid,p_user_id uuid,p_action text,p_status text default null,p_risk text default null,p_level text default null,p_reason text default null,p_notes text default null,p_next_review_due_at timestamptz default null,p_expires_at timestamptz default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare oldp public.zynth_kyc_profiles%rowtype; newp public.zynth_kyc_profiles%rowtype; begin if auth.uid() is null or auth.uid()<>p_admin_id or not public.zynth_has_role(auth.uid(),'admin') then raise exception 'ADMIN_AUTHORIZATION_REQUIRED'; end if; select * into oldp from public.zynth_kyc_profiles where user_id=p_user_id for update; if not found then insert into public.zynth_kyc_profiles(user_id) values(p_user_id) returning * into oldp; end if; if p_action not in ('REQUESTED_INFORMATION','APPROVED','REJECTED','SUSPENDED','REVERIFICATION_REQUIRED','EXPIRED','RISK_CHANGED') then raise exception 'INVALID_KYC_ACTION'; end if; if p_status is not null and p_status not in ('NOT_STARTED','PENDING','IN_REVIEW','VERIFIED','REJECTED','EXPIRED','REVERIFICATION_REQUIRED','SUSPENDED') then raise exception 'INVALID_KYC_STATUS'; end if; if p_risk is not null and p_risk not in ('LOW','MEDIUM','HIGH','CRITICAL') then raise exception 'INVALID_RISK_CLASSIFICATION'; end if; if p_level is not null and p_level not in ('NONE','BASIC','STANDARD','ENHANCED') then raise exception 'INVALID_VERIFICATION_LEVEL'; end if;
update public.zynth_kyc_profiles set status=coalesce(p_status,status),risk_classification=coalesce(p_risk,risk_classification),verification_level=coalesce(p_level,verification_level),risk_reason=case when p_risk is not null then nullif(trim(p_reason),'') else risk_reason end,risk_reviewed_at=case when p_risk is not null then now() else risk_reviewed_at end,next_review_due_at=coalesce(p_next_review_due_at,next_review_due_at),expires_at=coalesce(p_expires_at,expires_at),verified_at=case when coalesce(p_status,status)='VERIFIED' then coalesce(verified_at,now()) else verified_at end,suspended_at=case when coalesce(p_status,status)='SUSPENDED' then now() else suspended_at end,updated_at=now() where user_id=p_user_id returning * into newp;
update public.users set kyc_verified=(newp.status='VERIFIED'),updated_at=now() where id=p_user_id;
insert into public.zynth_kyc_review_history(user_id,reviewer_user_id,action,from_status,to_status,from_risk_classification,to_risk_classification,reason,notes) values(p_user_id,auth.uid(),p_action,oldp.status,newp.status,oldp.risk_classification,newp.risk_classification,nullif(trim(p_reason),''),nullif(trim(p_notes),''));
insert into public.audit_logs(actor_user_id,action,target_type,target_id,metadata) values(auth.uid(),'kyc.'||lower(p_action),'user',p_user_id,jsonb_build_object('from_status',oldp.status,'to_status',newp.status,'from_risk',oldp.risk_classification,'to_risk',newp.risk_classification,'reason',nullif(trim(p_reason),''))); return jsonb_build_object('ok',true,'profile',to_jsonb(newp)); end $$;
create or replace function public.zynth_kyc_admin_document(p_admin_id uuid,p_document_id uuid,p_status text,p_rejection_reason text default null,p_provider text default null,p_reviewer uuid default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare d public.zynth_kyc_documents%rowtype; nd public.zynth_kyc_documents%rowtype; begin if auth.uid() is null or auth.uid()<>p_admin_id or not public.zynth_has_role(auth.uid(),'admin') then raise exception 'ADMIN_AUTHORIZATION_REQUIRED'; end if; if p_status not in ('PENDING','IN_REVIEW','VERIFIED','REJECTED','EXPIRED') then raise exception 'INVALID_DOCUMENT_STATUS'; end if; select * into d from public.zynth_kyc_documents where id=p_document_id for update; if not found then raise exception 'DOCUMENT_NOT_FOUND'; end if; update public.zynth_kyc_documents set verification_status=p_status,rejection_reason=case when p_status='REJECTED' then nullif(trim(p_rejection_reason),'') else null end,verification_provider=coalesce(nullif(trim(p_provider),''),verification_provider),reviewer_user_id=coalesce(p_reviewer,auth.uid()),verified_at=case when p_status='VERIFIED' then now() else verified_at end,updated_at=now() where id=p_document_id returning * into nd; insert into public.zynth_kyc_review_history(user_id,reviewer_user_id,action,reason,metadata) values(d.user_id,auth.uid(),'DOCUMENT_REVIEWED',nullif(trim(p_rejection_reason),''),jsonb_build_object('document_id',d.id,'from',d.verification_status,'to',nd.verification_status)); insert into public.audit_logs(actor_user_id,action,target_type,target_id,metadata) values(auth.uid(),'kyc.document_reviewed','user',d.user_id,jsonb_build_object('document_id',d.id,'from',d.verification_status,'to',nd.verification_status)); return jsonb_build_object('ok',true,'status',nd.verification_status); end $$;
create or replace function public.zynth_kyc_admin_screening(p_admin_id uuid,p_user_id uuid,p_type text,p_result text,p_provider text default null,p_review_status text default 'IN_REVIEW',p_notes text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare sid uuid; begin if auth.uid() is null or auth.uid()<>p_admin_id or not public.zynth_has_role(auth.uid(),'admin') then raise exception 'ADMIN_AUTHORIZATION_REQUIRED'; end if; if p_type not in ('PEP','SANCTIONS') then raise exception 'INVALID_SCREENING_TYPE'; end if; if p_result not in ('NOT_SCREENED','CLEAR','MATCH','POSSIBLE_MATCH','UNAVAILABLE','ESCALATED') then raise exception 'INVALID_SCREENING_RESULT'; end if; if p_review_status not in ('NOT_REVIEWED','CLEAR','IN_REVIEW','CONFIRMED','FALSE_POSITIVE') then raise exception 'INVALID_SCREENING_REVIEW_STATUS'; end if; insert into public.zynth_kyc_screenings(user_id,screening_type,screened,result,provider,screened_at,review_status,reviewer_user_id,review_notes) values(p_user_id,p_type,true,p_result,nullif(trim(p_provider),''),now(),p_review_status,auth.uid(),nullif(trim(p_notes),'')) returning id into sid; insert into public.zynth_kyc_review_history(user_id,reviewer_user_id,action,notes,metadata) values(p_user_id,auth.uid(),'SCREENING_REVIEWED',p_notes,jsonb_build_object('screening_id',sid,'type',p_type,'result',p_result,'review_status',p_review_status)); insert into public.audit_logs(actor_user_id,action,target_type,target_id,metadata) values(auth.uid(),'kyc.screening_reviewed','user',p_user_id,jsonb_build_object('screening_id',sid,'type',p_type,'result',p_result,'review_status',p_review_status)); return jsonb_build_object('ok',true,'screening_id',sid); end $$;
revoke all on function public.zynth_kyc_ensure_profile() from public,anon; revoke all on function public.zynth_kyc_profile() from public,anon; revoke all on function public.zynth_kyc_submit_profile(text,text,text,date,text,text,text,text,text,jsonb) from public,anon; revoke all on function public.zynth_kyc_submit_document(text,text,text,text,date) from public,anon; revoke all on function public.zynth_kyc_admin_list(uuid,text,text,text,int,int) from public,anon; revoke all on function public.zynth_kyc_admin_detail(uuid,uuid) from public,anon; revoke all on function public.zynth_kyc_admin_update(uuid,uuid,text,text,text,text,text,text,timestamptz,timestamptz) from public,anon; revoke all on function public.zynth_kyc_admin_document(uuid,uuid,text,text,text,uuid) from public,anon; revoke all on function public.zynth_kyc_admin_screening(uuid,uuid,text,text,text,text,text) from public,anon;
grant execute on function public.zynth_kyc_ensure_profile() to authenticated; grant execute on function public.zynth_kyc_profile() to authenticated; grant execute on function public.zynth_kyc_submit_profile(text,text,text,date,text,text,text,text,text,jsonb) to authenticated; grant execute on function public.zynth_kyc_submit_document(text,text,text,text,date) to authenticated; grant execute on function public.zynth_kyc_admin_list(uuid,text,text,text,int,int) to authenticated; grant execute on function public.zynth_kyc_admin_detail(uuid,uuid) to authenticated; grant execute on function public.zynth_kyc_admin_update(uuid,uuid,text,text,text,text,text,text,timestamptz,timestamptz) to authenticated; grant execute on function public.zynth_kyc_admin_document(uuid,uuid,text,text,text,uuid) to authenticated; grant execute on function public.zynth_kyc_admin_screening(uuid,uuid,text,text,text,text,text) to authenticated;