import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { LockKeyhole, WalletCards } from "lucide-react";
export default async function DashboardPage(){
 const supabase=await createSupabaseServerClient();
 const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login");
 const {data:profile}=await supabase.from("users").select("full_name,role,main_wallet_balance,locked_vault_balance").eq("id",user.id).single();
 const {data:vaults}=await supabase.from("vaults").select("id,principal_amount,expected_yield,maturity_date,status").order("created_at",{ascending:false}).limit(5);
 const first=(profile?.full_name||"U").slice(0,1).toUpperCase();
 return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">Z</span><span>ZYNTH</span></div><div className="side-label">PERSONAL</div><nav><a className="nav-item active" href="/dashboard">Overview</a><a className="nav-item" href="/dashboard/vaults">Vaults</a><a className="nav-item" href="/dashboard/transactions">Transactions</a></nav><div className="side-bottom"><div className="secure"><LockKeyhole size={16}/>Secure account</div><form action="/auth/signout" method="post"><button className="profile-mini"><span className="avatar">{first}</span><span><b>{profile?.full_name||"Account"}</b><small>{profile?.role||"user"}</small></span></button></form></div></aside><section className="content"><header className="topbar"><div><span className="eyebrow">ZYNTH / DASHBOARD</span><h1>Good to see you.</h1></div><a className="fund-btn" href="/dashboard/vaults">Open a vault</a></header><section className="stats"><div className="stat"><div className="stat-icon"><WalletCards size={18}/></div><span>Available balance</span><b>₦{Number(profile?.main_wallet_balance||0).toLocaleString("en-NG",{minimumFractionDigits:2})}</b></div><div className="stat"><div className="stat-icon"><LockKeyhole size={18}/></div><span>Locked in vaults</span><b>₦{Number(profile?.locked_vault_balance||0).toLocaleString("en-NG",{minimumFractionDigits:2})}</b></div><div className="stat"><span>Active vaults</span><b>{(vaults||[]).filter(v=>v.status==="active").length}</b></div></section><section className="panel"><div className="panel-head"><div><span className="muted">YOUR VAULTS</span><h2>5-day cycles</h2></div><a className="ghost" href="/dashboard/vaults">Manage</a></div>{vaults?.length?<div className="vault-list">{vaults.map(v=><div className="vault-row" key={v.id}><div><b>₦{Number(v.principal_amount).toLocaleString("en-NG",{minimumFractionDigits:2})}</b><small>{v.status} · matures {new Date(v.maturity_date).toLocaleDateString("en-NG")}</small></div><strong>+₦{Number(v.expected_yield).toLocaleString("en-NG",{minimumFractionDigits:2})}</strong></div>)}</div>:<p className="copy">No vaults yet. Fund your wallet and open your first cycle when you are ready.</p>}</section></section></main>
}