"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,BarChart3,Clock3,Gauge,ShieldCheck,WalletCards} from "lucide-react";

const money=(n:any)=>n==null||!Number.isFinite(Number(n))?"Not configured":"₦"+Number(n).toLocaleString("en-NG",{maximumFractionDigits:0});
const pct=(n:any)=>n==null||!Number.isFinite(Number(n))?"—":(Number(n)>=0?"+":"")+Number(n).toFixed(2)+"%";
const labels:any={"7d":"7D","30d":"30D","90d":"90D","since_inception":"Since inception"};

function Chart({series}:{series:any[]}){if(!series?.length)return <div className="strategy-chart-empty"><BarChart3 size={22}/><span>No confirmed NAV history yet.</span></div>;const w=900,h=280,p=24,v=series.map(x=>Number(x.nav)),min=Math.min(...v),max=Math.max(...v),range=max-min||1,pts=series.map((x,i)=>{const xx=p+i/Math.max(series.length-1,1)*(w-p*2),yy=h-p-(Number(x.nav)-min)/range*(h-p*2);return xx+","+yy}).join(" ");return <div className="strategy-chart"><svg viewBox={"0 0 "+w+" "+h}><polyline points={pts} fill="none" className="chart-line"/></svg><div className="chart-caption"><span>{series[0]?.date}</span><b>₦{Number(series[series.length-1]?.nav||0).toFixed(4)}</b><span>{series[series.length-1]?.date}</span></div></div>}

export default function StrategyPage({params}:{params:{id:string}}){
 const[period,setPeriod]=useState("since_inception"),[d,setD]=useState<any>(),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{setLoading(true);fetch("/api/strategies/"+params.id+"/intelligence?period="+period,{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw Error(x.error||"Unable to load strategy.");return x}).then(setD).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[params.id,period]);
 if(loading&&!d)return <section className="dashboard-content dashboard-spacing-page"><div className="premium-empty"><BarChart3 size={22}/><h3>Loading strategy intelligence</h3></div></section>;
 if(error)return <section className="dashboard-content dashboard-spacing-page"><div className="notice">{error}</div></section>;
 const s=d?.strategy||{},p=d?.performance||{},r=d?.risk||{},b=d?.behaviour||{},c=d?.capacity||{},l=d?.liquidity||{};
 const redemption=l.redemption_window_days==null?"Not configured":l.redemption_window_days===1?"Daily":"Every "+l.redemption_window_days+" days";
 const processing=l.processing_time_min_business_days==null?"Not configured":l.processing_time_max_business_days==null?l.processing_time_min_business_days+" business day":l.processing_time_min_business_days+"–"+l.processing_time_max_business_days+" business days";
 const lock=l.lock_period_days==null?"Not configured":l.lock_period_days+" day"+(l.lock_period_days===1?"":"s");
 return <section className="dashboard-content dashboard-spacing-page strategy-intelligence-page">
  <header className="dashboard-header premium-header"><div><span className="eyebrow">ZYNTH / STRATEGY INTELLIGENCE</span><h1>{s.name||"Strategy"}</h1><p>{s.description||"Strategy performance, risk, behaviour, capacity and liquidity."}</p></div><Link className="fund-btn secondary-dark" href="/dashboard/investments"><ArrowLeft size={16}/> Investments</Link></header>
  <section className="strategy-intelligence-hero"><div><span>CURRENT NAV</span><strong>₦{Number(s.nav||0).toFixed(4)}</strong></div><div><span>{labels[period]} PERFORMANCE</span><strong>{pct(p.return_pct)}</strong></div><div><span>CURRENT DRAWDOWN</span><strong>{pct(b.current_drawdown_pct)}</strong></div></section>
  <section className="strategy-period-tabs">{(Object.entries(labels) as [string,string][]).map(([k,v])=><button key={k} className={period===k?"active":""} onClick={()=>setPeriod(k)}>{v}</button>)}</section>
  <section className="panel"><div className="panel-head"><div><span className="muted">PERFORMANCE</span><h2>NAV history</h2></div><span className="secure-chip"><ShieldCheck size={12}/> Confirmed NAV</span></div><Chart series={d?.series||[]}/><div className="strategy-stat-grid"><div><span>Return</span><b>{pct(p.return_pct)}</b></div><div><span>From</span><b>{p.start_date||"—"}</b></div><div><span>To</span><b>{p.end_date||"—"}</b></div></div></section>
  <div className="strategy-section-grid"><section className="panel"><div className="panel-head"><div><span className="muted">RISK</span><h2>Risk profile</h2></div><Gauge size={18}/></div><div className="strategy-metric-list">{[["Maximum drawdown",pct(r.maximum_drawdown_pct),"Peak-to-trough decline"],["Worst day",pct(r.worst_day_pct),"Lowest daily return"],["Best day",pct(r.best_day_pct),"Highest daily return"],["Volatility",r.volatility_pct==null?"—":Number(r.volatility_pct).toFixed(2)+"%","Daily return standard deviation"],["Recovery period",r.recovery_days==null?"Not recovered":r.recovery_days+" days","Time to recover maximum drawdown"],["Losing days",r.losing_days+" ("+Number(r.losing_days_pct||0).toFixed(1)+"%)","Observed return days"],["Winning days",r.winning_days+" ("+Number(r.winning_days_pct||0).toFixed(1)+"%)","Observed return days"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></section>
  <section className="panel"><div className="panel-head"><div><span className="muted">BEHAVIOUR</span><h2>Return behaviour</h2></div></div><div className="strategy-metric-list">{[["Average monthly return",pct(b.average_monthly_return_pct)],["Average winning month",pct(b.average_winning_month_pct)],["Average losing month",pct(b.average_losing_month_pct)],["Current drawdown",pct(b.current_drawdown_pct)],["Current streak",b.current_streak?(b.current_streak+" consecutive "+String(b.current_streak_direction).toLowerCase()+" days"):"No active streak"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></section></div>
  <div className="strategy-section-grid"><section className="panel"><div className="panel-head"><div><span className="muted">CAPACITY</span><h2>Capital capacity</h2></div><WalletCards size={18}/></div><div className="capacity-highlight"><div><span>Current AUM</span><strong>{money(c.current_aum)}</strong></div><div><span>Maximum</span><strong>{money(c.maximum_capacity)}</strong></div><div><span>Available</span><strong>{money(c.available_capacity)}</strong></div></div><div className={"capacity-status "+(c.accepting_new_capital?"open":"full")}><span>{c.accepting_new_capital?"Accepting new capital":"Capacity reached"}</span></div></section>
  <section className="panel"><div className="panel-head"><div><span className="muted">LIQUIDITY</span><h2>Redemption terms</h2></div><Clock3 size={18}/></div><div className="strategy-metric-list"><div><span>Redemption window</span><b>{redemption}</b></div><div><span>Processing time</span><b>{processing}</b></div><div><span>Lock period</span><b>{lock}</b></div></div></section></div>
 </section>;
}